import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Camera, ShieldCheck, Trash2 } from "lucide-react";
import { ChangeEvent, useState } from "react";
import { Link } from "wouter";
import { toast } from "sonner";

export default function AccountProfileMediaPage() {
  const { isAuthenticated } = useAuth();
  const utils = trpc.useUtils();
  const profile = trpc.profile.get.useQuery(undefined, { enabled: isAuthenticated });
  const [file, setFile] = useState<File | null>(null);
  const upload = trpc.media.uploadAvatar.useMutation({ onSuccess: () => { toast.success("Profile photo updated."); setFile(null); void utils.profile.get.invalidate(); }, onError: error => toast.error(error.message) });
  const remove = trpc.media.removeAvatar.useMutation({ onSuccess: () => { toast.success("Profile photo removed."); void utils.profile.get.invalidate(); }, onError: error => toast.error(error.message) });
  const visibility = trpc.media.setAvatarVisibility.useMutation({ onSuccess: () => { toast.success("Profile photo privacy updated."); void utils.profile.get.invalidate(); }, onError: error => toast.error(error.message) });
  const select = (event: ChangeEvent<HTMLInputElement>) => { const selected = event.target.files?.[0] ?? null; if (!selected) return; if (!["image/jpeg", "image/png", "image/webp"].includes(selected.type) || selected.size > 2 * 1024 * 1024) { toast.error("Choose a JPEG, PNG, or WebP image up to 2 MB."); event.target.value = ""; return; } setFile(selected); };
  const save = async () => { if (!file) return; const dataUrl = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(new Error("The selected image could not be read.")); reader.readAsDataURL(file); }); upload.mutate({ filename: file.name, mimeType: file.type as "image/jpeg" | "image/png" | "image/webp", dataUrl, makePublic: Boolean(profile.data?.isAvatarPublic) }); };
  if (!isAuthenticated) return <main className="page-shell py-20 text-center"><ShieldCheck className="mx-auto text-[#00843d]" size={40}/><h1 className="mt-4 text-3xl font-extrabold">Sign in to manage your profile photo</h1><Link href="/login"><Button className="mt-6 bg-[#e31b23]">Sign in</Button></Link></main>;
  return <main className="page-shell py-8"><p className="eyebrow text-[#00843d]">MY ACCOUNT</p><div className="mt-2 flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-3xl font-extrabold">Profile photo</h1><p className="mt-2 max-w-xl text-sm text-slate-600">Use a real photo to make your reviews and messages more recognizable. You control whether it appears publicly with reviews.</p></div><Link href="/account/profile"><Button variant="outline">Back to profile</Button></Link></div><section className="mt-7 max-w-2xl rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div className="flex flex-col gap-6 sm:flex-row sm:items-center"><div className="flex h-28 w-28 shrink-0 items-center justify-center overflow-hidden rounded-full bg-[#eaf7ef] ring-4 ring-white shadow"><>{profile.data?.avatarUrl ? <img src={profile.data.avatarUrl} alt="Your profile" className="h-full w-full object-cover"/> : <Camera className="text-[#00843d]" size={34}/>}</></div><div className="flex-1"><p className="font-extrabold">Your account photo</p><p className="mt-1 text-sm text-slate-500">JPEG, PNG, or WebP only. Maximum 2 MB. Files are validated and stored by the marketplace server.</p><input className="mt-4 block w-full text-sm" type="file" accept="image/jpeg,image/png,image/webp" onChange={select}/>{file && <p className="mt-2 text-xs font-bold text-[#006b32]">Ready: {file.name}</p>}<Button className="mt-4 bg-[#00843d]" disabled={!file || upload.isPending} onClick={() => void save()}>{upload.isPending ? "Uploading…" : "Upload profile photo"}</Button></div></div><div className="mt-6 border-t pt-5"><label className="flex items-start gap-3 text-sm"><input className="mt-1" type="checkbox" checked={Boolean(profile.data?.isAvatarPublic)} disabled={visibility.isPending || !profile.data?.avatarUrl} onChange={event => visibility.mutate({ isPublic: event.target.checked })}/><span><b>Show this photo with my public reviews.</b><br/><span className="text-slate-500">Leave this off to keep your photo visible only in your account workspace.</span></span></label>{profile.data?.avatarUrl && <Button variant="outline" className="mt-5 text-[#b91c1c]" disabled={remove.isPending} onClick={() => remove.mutate()}><Trash2 size={16}/>{remove.isPending ? "Removing…" : "Remove profile photo"}</Button>}</div></section></main>;
}
