import { useAuth } from "@/_core/hooks/useAuth";
import { MarketplaceWorkspaceShell, type WorkspaceNavItem } from "@/components/MarketplaceWorkspaceShell";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { naira } from "@/lib/marketplace";
import { Bell, Heart, LayoutDashboard, LogOut, MessageCircle, PackageCheck, Settings, ShoppingCart, Star, Store, Tag, UserRound } from "lucide-react";
import { Link, useLocation } from "wouter";
import { toast } from "sonner";

const buyerNavigation: WorkspaceNavItem[] = [
  { label: "Overview", href: "/account", icon: LayoutDashboard },
  { label: "My orders", href: "/account/orders", icon: PackageCheck },
  { label: "Saved listings", href: "/account/favorites", icon: Heart },
  { label: "My offers", href: "/account/offers", icon: Tag },
  { label: "Messages", href: "/account/messages", icon: MessageCircle },
  { label: "Notifications", href: "/account/notifications", icon: Bell },
  { label: "Reviews", href: "/account/reviews", icon: Star },
  { label: "Profile & security", href: "/account/settings", icon: Settings },
];

export default function AccountPage() {
  const { user, isAuthenticated, loading, logout } = useAuth();
  const [, navigate] = useLocation();
  const dashboard = trpc.buyer.dashboard.useQuery(undefined, { enabled: Boolean(isAuthenticated && user) });
  const signOut = async () => { try { await logout(); toast.success("You have been signed out."); navigate("/"); } catch { toast.error("Unable to sign out. Please try again."); } };

  if (loading) return <main className="page-shell py-16">Loading your account…</main>;
  if (!isAuthenticated || !user) return <main className="page-shell py-20 text-center"><UserRound className="mx-auto text-[#00843d]" size={42} /><h1 className="mt-4 text-3xl font-extrabold">Sign in to access your account</h1><p className="mt-2 text-slate-600">Your buyer dashboard and marketplace tools are private to your secure account.</p><Link href="/login"><Button className="mt-6 bg-[#e31b23]">Log in</Button></Link><Link href="/register" className="mt-4 block text-sm font-bold text-[#00843d]">Create an account</Link></main>;

  const summary = dashboard.data;
  const isSeller = ["SELLER", "ADMIN", "SUPER_ADMIN"].includes(user.role);
  const nav = buyerNavigation.map(item => item.href === "/account/orders" && summary?.activeOrders ? { ...item, badge: summary.activeOrders } : item.href === "/account/notifications" && summary?.unreadUpdates ? { ...item, badge: summary.unreadUpdates } : item);

  return <MarketplaceWorkspaceShell kind="buyer" eyebrow="BUYER ACCOUNT" title={`Welcome back, ${user.name ?? "ESUT shopper"}`} subtitle="Follow your campus-pickup orders, saved listings, offers, and secure seller conversations from one organized account." navItems={nav} userName={user.name} onLogout={signOut} utility={<Link href="/cart" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-sm font-bold text-slate-700 hover:border-[#e31b23] hover:text-[#b91c1c]"><ShoppingCart size={16} /> Cart</Link>}>
    {dashboard.isError && <div role="alert" className="mb-5 rounded-2xl bg-[#fff3f3] p-5 text-sm text-[#b91c1c] ring-1 ring-[#fecaca]"><p className="font-extrabold">We could not load your account summary.</p><p className="mt-1">Your orders, messages, and account controls remain private and available through the navigation.</p><Button size="sm" variant="outline" className="mt-3" onClick={() => dashboard.refetch()}>Try again</Button></div>}
    <section aria-label="Buyer purchase summary" className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<PackageCheck />} tone="green" label="Orders to collect" value={summary?.ordersToCollect ?? "—"} hint={summary?.ordersToCollect ? "Ready for campus pickup" : "No pickup is ready yet"} /><Metric icon={<ShoppingCart />} tone="blue" label="Active orders" value={summary?.activeOrders ?? "—"} hint="Orders progressing through pickup" /><Metric icon={<Heart />} tone="red" label="Saved listings" value={summary?.savedListings ?? "—"} hint="Listings saved to your account" /><Metric icon={<Bell />} tone="gold" label="Unread updates" value={summary?.unreadUpdates ?? "—"} hint="Order, offer, and message notices" /></section>
    <section className="mt-6 grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><article className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-6"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.14em] text-[#00843d]">PICKUP PROGRESS</p><h2 className="mt-1 text-xl font-black">Recent orders</h2><p className="mt-1 text-sm text-slate-500">Follow the actual status of your campus-pickup purchases.</p></div><Link href="/account/orders" className="text-sm font-bold text-[#00843d]">View all</Link></div>{dashboard.isLoading ? <div className="mt-5 space-y-3"><div className="h-16 animate-pulse rounded-xl bg-slate-100" /><div className="h-16 animate-pulse rounded-xl bg-slate-100" /></div> : summary?.recentOrders.length ? <div className="mt-5 divide-y divide-slate-100">{summary.recentOrders.map(({ order, store }) => <Link href={`/account/orders/${order.publicId}`} key={order.id} className="flex items-center justify-between gap-4 py-4 transition hover:bg-slate-50"><div className="min-w-0"><p className="font-extrabold">{store.name}</p><p className="mt-1 truncate text-sm text-slate-500">{order.publicId} · {new Date(order.createdAt).toLocaleDateString("en-NG", { day: "numeric", month: "short" })}</p></div><div className="shrink-0 text-right"><p className="font-extrabold">{naira(order.totalKobo)}</p><span className={`mt-1 inline-flex rounded-full px-2 py-0.5 text-xs font-black ${order.status === "READY_FOR_PICKUP" ? "bg-[#eaf7ef] text-[#006b32]" : "bg-slate-100 text-slate-600"}`}>{order.status.replaceAll("_", " ")}</span></div></Link>)}</div> : <Empty icon={<PackageCheck size={26} />} title="No active purchases yet" copy="Browse approved listings and start a campus-pickup order when you find what you need." href="/explore" label="Explore marketplace" />}</article>
      <article className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-6"><p className="text-xs font-black uppercase tracking-[.14em] text-[#e31b23]">QUICK ACTIONS</p><h2 className="mt-1 text-xl font-black">Manage your shopping</h2><div className="mt-5 grid gap-3"><QuickAction href="/cart" icon={<ShoppingCart size={18} />} title="Review cart" detail="Continue to protected pickup checkout" /><QuickAction href="/account/orders" icon={<PackageCheck size={18} />} title="Pickup details" detail={summary?.ordersToCollect ? `${summary.ordersToCollect} order${summary.ordersToCollect === 1 ? "" : "s"} ready to collect` : "Track current order status"} /><QuickAction href="/account/favorites" icon={<Heart size={18} />} title="Saved listings" detail={summary?.savedListings ? `${summary.savedListings} listing${summary.savedListings === 1 ? "" : "s"} saved` : "Keep products for later"} /><QuickAction href="/account/messages" icon={<MessageCircle size={18} />} title="Message sellers" detail="Continue participant-only conversations" /></div></article></section>
    <section className="mt-6 grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><article className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[.14em] text-[#00843d]">ACCOUNT UPDATES</p><h2 className="mt-1 text-xl font-black">Recent activity</h2></div><Link href="/account/notifications" className="text-sm font-bold text-[#00843d]">Notifications</Link></div>{dashboard.isLoading ? <div className="mt-5 h-24 animate-pulse rounded-xl bg-slate-100" /> : summary?.recentUpdates.length ? <div className="mt-5 divide-y divide-slate-100">{summary.recentUpdates.map(update => <Link href={update.targetRoute || "/account/notifications"} key={update.id} className="block py-4 transition hover:bg-slate-50"><div className="flex items-start justify-between gap-3"><div><p className="font-extrabold">{update.title}</p><p className="mt-1 text-sm leading-6 text-slate-500">{update.message}</p></div>{!update.isRead && <span className="mt-1 h-2.5 w-2.5 shrink-0 rounded-full bg-[#e31b23]" aria-label="Unread update" />}</div></Link>)}</div> : <Empty icon={<Bell size={26} />} title="No account updates yet" copy="Order, offer, and message updates will appear here when they are relevant to your account." href="/explore" label="Browse listings" />}</article>
      <article className="rounded-3xl bg-[#08243b] p-5 text-white shadow-sm sm:p-6"><p className="text-xs font-black uppercase tracking-[.14em] text-[#f5b700]">SHOP WITH CONFIDENCE</p><h2 className="mt-1 text-xl font-black">Your campus purchase rules</h2><div className="mt-6 space-y-3 text-sm leading-6 text-slate-200"><p>• Confirm stock and final pricing through the marketplace checkout flow.</p><p>• Arrange pickup with the seller after your order is confirmed.</p><p>• Pay cash on pickup only when you collect the order.</p></div><Link href="/account/settings" className="mt-6 inline-flex text-sm font-bold text-[#f5b700]">Profile & security →</Link>{isSeller && <Link href="/seller" className="mt-4 flex items-center gap-2 rounded-2xl bg-white/10 p-4 text-sm font-bold text-white ring-1 ring-white/10"><Store size={18} className="text-[#f5b700]" /> Open seller workspace</Link>}</article></section>
  </MarketplaceWorkspaceShell>;
}

function Metric({ icon, tone, label, value, hint }: { icon: React.ReactNode; tone: "green" | "blue" | "gold" | "red"; label: string; value: string | number; hint: string }) { const palette = { green: "bg-[#eaf7ef] text-[#006b32]", blue: "bg-[#edf6ff] text-[#0570c0]", gold: "bg-[#fff7e6] text-[#8a6500]", red: "bg-[#fff3f3] text-[#b91c1c]" }[tone]; return <article className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><span className={`flex h-10 w-10 items-center justify-center rounded-xl ${palette}`}>{icon}</span><p className="mt-5 text-2xl font-black">{value}</p><p className="mt-1 font-bold">{label}</p><p className="mt-1 text-xs leading-5 text-slate-500">{hint}</p></article>; }
function QuickAction({ href, icon, title, detail }: { href: string; icon: React.ReactNode; title: string; detail: string }) { return <Link href={href} className="flex items-center gap-3 rounded-2xl border border-slate-200 p-4 transition hover:border-[#00843d] hover:bg-[#f4f8f5]"><span className="text-[#00843d]">{icon}</span><span className="min-w-0 flex-1"><span className="block font-extrabold">{title}</span><span className="mt-0.5 block text-xs text-slate-500">{detail}</span></span><span aria-hidden className="text-lg font-black text-[#00843d]">→</span></Link>; }
function Empty({ icon, title, copy, href, label }: { icon: React.ReactNode; title: string; copy: string; href: string; label: string }) { return <div className="mt-5 rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-7 text-center"><span className="mx-auto flex h-11 w-11 items-center justify-center rounded-full bg-white text-[#00843d] shadow-sm">{icon}</span><p className="mt-3 font-extrabold">{title}</p><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-500">{copy}</p><Link href={href} className="mt-4 inline-flex text-sm font-bold text-[#00843d]">{label}</Link></div>; }
