import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Activity, LockKeyhole, MonitorSmartphone, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import { toast } from "sonner";

const readableEvent = (value: string) => value.replaceAll("_", " ").toLowerCase().replace(/^./, char => char.toUpperCase());

export default function AccountSecurityPage() {
  const { isAuthenticated } = useAuth();
  const utils = trpc.useUtils();
  const security = trpc.auth.security.useQuery(undefined, { enabled: isAuthenticated });
  const revokeOthers = trpc.auth.revokeOtherSessions.useMutation({
    onSuccess: ({ revokedCount }) => { toast.success(revokedCount ? `${revokedCount} other session${revokedCount === 1 ? "" : "s"} signed out.` : "No other active sessions found."); void utils.auth.security.invalidate(); },
    onError: error => toast.error(error.message),
  });
  if (!isAuthenticated) return <main className="page-shell py-20 text-center"><ShieldCheck className="mx-auto text-[#00843d]" size={40}/><h1 className="mt-4 text-3xl font-extrabold">Sign in to review account security</h1><p className="mx-auto mt-3 max-w-md text-sm text-slate-600">Your session and security activity are available only to you.</p><Link href="/login"><Button className="mt-6 bg-[#e31b23]">Sign in</Button></Link></main>;
  return <main className="page-shell py-8"><Link href="/account" className="inline-flex items-center text-sm font-bold text-[#00843d] underline-offset-4 hover:underline">← Back to account</Link><p className="eyebrow mt-5 text-[#00843d]">MY ACCOUNT</p><div className="mt-2 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-3xl font-extrabold">Security and devices</h1><p className="mt-2 max-w-2xl text-sm text-slate-600">Review signed-in devices and recent security activity. We do not show passwords, session tokens, or raw IP addresses.</p></div><Link href="/account/settings"><Button variant="outline">Account settings</Button></Link></div>
    {security.isLoading ? <section className="mt-7 rounded-2xl bg-white p-8 text-center text-slate-500 shadow-sm ring-1 ring-slate-200">Loading your security information…</section> : security.isError ? <section className="mt-7 rounded-2xl bg-[#fff3f3] p-8 text-center text-[#b91c1c] ring-1 ring-[#fecaca]"><p>We could not load your security information.</p><Button className="mt-4" variant="outline" onClick={() => security.refetch()}>Try again</Button></section> : <><section className="mt-7 rounded-2xl bg-[#08243b] p-6 text-white"><div className="flex items-start gap-4"><ShieldCheck className="shrink-0 text-[#f5b700]" size={32}/><div><h2 className="font-extrabold">Your account is protected by server-verified sessions</h2><p className="mt-1 text-sm text-slate-200">Signing out another device revokes its session on the server. It cannot continue by refreshing its browser.</p></div></div><Button className="mt-5 bg-white text-[#08243b] hover:bg-slate-100" disabled={revokeOthers.isPending} onClick={() => revokeOthers.mutate()}>{revokeOthers.isPending ? "Signing out devices…" : "Sign out other devices"}</Button></section>
      <section className="mt-6 grid gap-5 lg:grid-cols-[1.05fr_.95fr]"><div className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div className="flex items-center gap-2"><MonitorSmartphone className="text-[#00843d]" size={21}/><h2 className="font-extrabold">Active sessions</h2></div><p className="mt-1 text-sm text-slate-500">Devices currently permitted to use your account.</p><div className="mt-5 space-y-3">{security.data?.sessions.filter(session => session.status === "ACTIVE").length ? security.data.sessions.filter(session => session.status === "ACTIVE").map(session => <article key={session.id} className={`rounded-xl border p-4 ${session.isCurrent ? "border-[#00843d]/35 bg-[#eaf7ef]" : "border-slate-200 bg-slate-50"}`}><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-extrabold">{session.deviceLabel}</p><p className="mt-1 text-xs text-slate-500">Last active {new Date(session.lastActiveAt).toLocaleString()}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-black ${session.isCurrent ? "bg-[#00843d] text-white" : "bg-white text-slate-600 ring-1 ring-slate-200"}`}>{session.isCurrent ? "This device" : "Active"}</span></div></article>) : <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">No active session records are available yet. Sign out and back in once to create a protected device session.</p>}</div></div>
        <div className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div className="flex items-center gap-2"><Activity className="text-[#e31b23]" size={21}/><h2 className="font-extrabold">Recent security activity</h2></div><p className="mt-1 text-sm text-slate-500">Successful and blocked account activity, shown without sensitive identifiers.</p><div className="mt-5 space-y-3">{security.data?.events.length ? security.data.events.map(event => <article key={event.id} className="flex gap-3 rounded-xl bg-slate-50 p-3"><LockKeyhole className="mt-0.5 shrink-0 text-[#08243b]" size={17}/><div><p className="text-sm font-extrabold">{readableEvent(event.eventType)}</p>{event.deviceLabel ? <p className="mt-0.5 text-xs text-slate-500">{event.deviceLabel}</p> : null}<time className="mt-1 block text-xs text-slate-400">{new Date(event.createdAt).toLocaleString()}</time></div></article>) : <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">New sign-ins and security actions will appear here.</p>}</div></div></section></>}
  </main>;
}
