import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { condition, naira } from "@/lib/marketplace";
import { trpc } from "@/lib/trpc";
import { ArrowRight, BadgeCheck, Boxes, ChevronRight, Heart, MapPin, Menu, Package, Search, ShieldCheck, ShoppingCart, Sparkles, Store, UsersRound, X } from "lucide-react";
import { useState } from "react";
import { Link, useLocation } from "wouter";
import { toast } from "sonner";

const logo = "/manus-storage/esut-main-logo_0f99c6ab.png";
const categoryIcons: Record<string, string> = { Electronics: "⌁", Fashion: "✦", "Phones & Accessories": "◉", Books: "▤", "Hostel & Home": "⌂", "Food & Groceries": "◒", Services: "⌘", Computing: "⌗" };

function ProductCard({ row }: { row: any }) {
  const { listing, store, image } = row; const { isAuthenticated } = useAuth(); const [, go] = useLocation();
  const add = trpc.cart.add.useMutation({ onSuccess: () => { toast.success("Added to cart"); go("/cart"); }, onError: error => toast.error(error.message) });
  const save = trpc.favorites.toggle.useMutation({ onSuccess: data => toast.success(data.favorited ? "Saved to favorites" : "Removed from favorites"), onError: () => toast.error("Sign in to save products") });
  const discount = listing.compareAtPriceKobo ? Math.round((1 - listing.priceKobo / listing.compareAtPriceKobo) * 100) : 0;
  return <article className="product-card"><Link href={`/product/${listing.slug}`}><div className="product-visual relative aspect-[1/.8]">{image?.url ? <img src={image.url} alt={listing.title} className="h-full w-full object-cover"/> : <Package size={46} strokeWidth={1.3}/>}<span className="absolute left-3 top-3 rounded-md bg-white/95 px-2 py-1 text-[10px] font-extrabold text-[#006b32]">{condition(listing.condition)}</span>{discount > 0 && <span className="absolute bottom-3 left-3 rounded-md bg-[#e31b23] px-2 py-1 text-[10px] font-extrabold text-white">-{discount}%</span>}</div></Link><div className="p-4"><div className="flex justify-between gap-2"><Link href={`/product/${listing.slug}`}><h3 className="line-clamp-2 font-bold leading-5 text-[#111827] hover:text-[#00843d]">{listing.title}</h3></Link><button type="button" aria-label="Save product" className="shrink-0 text-slate-400 hover:text-[#e31b23]" onClick={() => isAuthenticated ? save.mutate({ listingId: listing.id }) : toast.error("Sign in to save products")}><Heart size={18}/></button></div><div className="mt-3 flex items-end gap-2"><strong className="text-lg text-[#e31b23]">{naira(listing.priceKobo)}</strong>{listing.compareAtPriceKobo && <span className="pb-0.5 text-xs text-slate-400 line-through">{naira(listing.compareAtPriceKobo)}</span>}</div><p className="mt-2 flex items-center gap-1 text-xs text-slate-500"><BadgeCheck size={14} className="text-[#00843d]"/>{store.name}</p><p className="mt-1 flex items-center gap-1 text-xs text-slate-500"><MapPin size={13}/>{listing.location}</p><Button className="mt-4 w-full bg-[#e31b23] hover:bg-[#c9161d]" size="sm" onClick={() => isAuthenticated ? add.mutate({ listingId: listing.id, quantity: 1 }) : toast.error("Sign in to add products")}>Add to cart</Button></div></article>;
}
function ProductSection({ eyebrow, title, rows, empty, accent = "#00843d" }: { eyebrow: string; title: string; rows: any[]; empty: string; accent?: string }) { return <section className="page-shell py-9"><div className="section-head"><div><p className="eyebrow" style={{ color: accent }}>{eyebrow}</p><h2>{title}</h2></div><Link href="/explore" className="view-link">View all <ArrowRight size={16}/></Link></div>{rows.length ? <div className="product-grid">{rows.slice(0, 8).map(row => <ProductCard key={row.listing.id} row={row}/>)}</div> : <div className="empty-panel"><Boxes size={34}/><p>{empty}</p></div>}</section>; }

export default function Home() {
  const home = trpc.marketplace.home.useQuery(); const [query, setQuery] = useState(""); const [mobileOpen, setMobileOpen] = useState(false); const [, go] = useLocation(); const { isAuthenticated, user } = useAuth();
  const data = home.data; const fresh = data?.listings ?? []; const deals = data?.todayDeals ?? []; const trending = data?.trending ?? []; const campusPicks = data?.campusPicks ?? []; const services = data?.services ?? [];
  return <div className="min-h-screen bg-[#f7f9fc]"><div className="announcement">Shop from verified ESUT sellers <span>•</span> Campus pickup available</div><header className="market-header"><div className="page-shell flex h-[76px] items-center gap-4"><Link href="/" className="flex shrink-0 items-center"><img src={logo} alt="ESUT Marketplace" className="h-14 w-14 object-contain"/><span className="hidden text-base font-black leading-4 text-[#111827] sm:block">ESUT<br/><em className="not-italic text-[#00843d]">Marketplace</em></span></Link><form className="hidden flex-1 md:block" onSubmit={event => { event.preventDefault(); go(`/explore?q=${encodeURIComponent(query)}`); }}><label className="searchbox"><Search size={19}/><input value={query} onChange={event => setQuery(event.target.value)} placeholder="What are you looking for today?"/><button type="submit">Search</button></label></form><nav className="ml-auto hidden items-center gap-4 lg:flex"><Link href="/cart" className="nav-icon"><ShoppingCart size={20}/><span>Cart</span></Link><Link href={isAuthenticated ? "/account" : "/login"} className="nav-icon"><UsersRound size={20}/><span>{isAuthenticated ? user?.name?.split(" ")[0] ?? "Account" : "Login"}</span></Link><Link href="/sell"><Button className="bg-[#00843d] hover:bg-[#006b32]">Sell on ESUT</Button></Link></nav><Link href="/cart" className="ml-auto lg:hidden"><ShoppingCart size={22}/></Link><button type="button" aria-label="Open navigation" className="lg:hidden" onClick={() => setMobileOpen(value => !value)}>{mobileOpen ? <X size={23}/> : <Menu size={23}/>}</button></div>{mobileOpen && <div className="border-t bg-white lg:hidden"><div className="page-shell grid gap-2 py-4"><Link href="/explore" onClick={() => setMobileOpen(false)} className="rounded-lg px-3 py-2 font-bold hover:bg-slate-50">Browse marketplace</Link><Link href={isAuthenticated ? "/account" : "/login"} onClick={() => setMobileOpen(false)} className="rounded-lg px-3 py-2 font-bold hover:bg-slate-50">{isAuthenticated ? "My account" : "Login"}</Link><Link href="/sell" onClick={() => setMobileOpen(false)} className="rounded-lg px-3 py-2 font-bold text-[#00843d] hover:bg-[#eaf7ef]">Sell on ESUT</Link></div></div>}<div className="border-t border-slate-100 bg-white"><div className="page-shell flex h-12 items-center gap-6 overflow-x-auto whitespace-nowrap text-sm font-semibold text-slate-600">{data?.categories.map(category => <Link key={category.id} href={`/category/${category.slug}`} className="hover:text-[#00843d]">{category.name}</Link>)}<Link href="/explore" className="flex items-center gap-1 text-[#00843d]">More <ChevronRight size={15}/></Link></div></div></header>
  <main><section className="page-shell py-6"><div className="hero-grid"><div className="hero-copy"><p className="eyebrow"><Sparkles size={15}/> ESUT CAMPUS MARKETPLACE</p><h1>Everything you need.<br/><span>Right around you.</span></h1><p>Discover products, services and trusted sellers from ESUT and beyond. Shop campus deals with confidence.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/explore"><Button size="lg" className="bg-[#e31b23] hover:bg-[#c9161d]">Shop now <ArrowRight size={18}/></Button></Link><Link href="/sell"><Button size="lg" variant="outline" className="border-[#00843d] text-[#006b32]">Start selling</Button></Link></div><div className="mt-10 flex gap-7"><div><strong>Campus pickup</strong><span>Easy collection</span></div><div><strong>Verified sellers</strong><span>Shop smarter</span></div></div></div><div className="hero-art"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="hero-cart"><ShoppingCart size={74}/></div><div className="float-card float-phone">◉<span>Phones</span></div><div className="float-card float-books">▤<span>Books</span></div><div className="float-card float-fashion">✦<span>Fashion</span></div><p className="art-caption">Campus<br/><b>Deals</b></p></div></div></section>
  <section className="page-shell py-6"><div className="section-head"><div><p className="eyebrow text-[#00843d]">DISCOVER MORE</p><h2>Shop by category</h2></div><Link href="/explore" className="view-link">View all <ArrowRight size={16}/></Link></div><div className="category-row">{(data?.categories ?? []).slice(0, 8).map(category => <Link href={`/category/${category.slug}`} key={category.id} className="category-tile"><span>{categoryIcons[category.name] ?? "◇"}</span><b>{category.name}</b><small>Explore now</small></Link>)}</div></section>
  <section className="deals-strip"><div className="page-shell flex flex-col gap-5 py-7 sm:flex-row sm:items-center sm:justify-between"><div><p className="eyebrow text-[#f5b700]">TODAY'S DEALS</p><h2>Price drops from active campus sellers.</h2></div><Link href="/explore"><Button className="bg-white text-[#111827] hover:bg-slate-100">Browse all listings <ArrowRight size={17}/></Button></Link></div></section>
  {home.isLoading ? <div className="page-shell py-12 text-slate-500">Loading marketplace collections…</div> : <><ProductSection eyebrow="JUST IN" title="Fresh arrivals" rows={fresh} empty="Listings will appear here as approved sellers publish them." accent="#e31b23"/><ProductSection eyebrow="SAVINGS" title="Today's Deals" rows={deals} empty="No active price-drop listings are available today." accent="#f5b700"/><ProductSection eyebrow="POPULAR NOW" title="Trending on campus" rows={trending} empty="Trending listings will appear once the marketplace receives more activity."/><ProductSection eyebrow="STUDENT ESSENTIALS" title="Campus Picks" rows={campusPicks} empty="Campus-relevant listings will appear as sellers publish them." accent="#e31b23"/>
  <section className="page-shell py-9"><div className="section-head"><div><p className="eyebrow text-[#00843d]">TRUSTED STORES</p><h2>Verified Sellers</h2></div><Link href="/explore" className="view-link">Browse listings <ArrowRight size={16}/></Link></div>{data?.stores.length ? <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{data.stores.map(store => <article key={store.id} className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div className="flex items-start gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#eaf7ef] text-[#00843d]"><Store size={21}/></span><div><h3 className="font-extrabold">{store.name}</h3><p className="mt-1 flex items-center gap-1 text-xs text-slate-500"><MapPin size={13}/>{store.location}</p></div></div><p className="mt-5 flex items-center gap-1 text-sm font-bold text-[#00843d]"><ShieldCheck size={16}/>Verified seller</p><Link href="/explore" className="mt-5 inline-block text-sm font-bold text-[#00843d]">Explore marketplace <ArrowRight className="inline" size={14}/></Link></article>)}</div> : <div className="empty-panel"><Store size={34}/><p>Verified stores will appear after administrators approve their applications.</p></div>}</section>
  <section className="page-shell py-9"><div className="section-head"><div><p className="eyebrow text-[#e31b23]">PICKUP PROVEN</p><h2>Popular Stores</h2></div><Link href="/explore" className="view-link">Browse listings <ArrowRight size={16}/></Link></div>{data?.popularStores.length ? <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{data.popularStores.map(store => <article key={store.id} className="rounded-2xl border border-[#e31b23]/10 bg-[#fffafa] p-6"><Store className="text-[#e31b23]"/><h3 className="mt-4 font-extrabold">{store.name}</h3><p className="mt-1 text-sm text-slate-600">{store.location}</p><p className="mt-4 text-sm font-bold text-[#006b32]">{store.completedOrderCount ? `${store.completedOrderCount} completed pickup${store.completedOrderCount === 1 ? "" : "s"}` : "New verified store"}</p></article>)}</div> : <div className="empty-panel"><Store size={34}/><p>Popular stores will appear as campus pickups are completed.</p></div>}</section>
  <ProductSection eyebrow="CAMPUS SERVICES" title="Book a campus service" rows={services} empty="Service listings will appear here when approved sellers publish them." accent="#00843d"/></>}
  <section className="page-shell py-8"><div className="trust-grid"><div><span className="trust-icon"><ShieldCheck/></span><h2>Why ESUT Marketplace</h2><p>Find verified sellers, complete a protected campus-pickup order, and keep your marketplace communication inside your account.</p><Link href="/explore" className="view-link">Explore verified listings <ArrowRight size={16}/></Link></div><div className="trust-points"><p><BadgeCheck/> ESUT community marketplace</p><p><BadgeCheck/> Seller verification workflow</p><p><BadgeCheck/> Secure account architecture</p><p><BadgeCheck/> Campus pickup and cash-on-pickup</p></div></div></section>
  <section className="seller-banner"><div className="page-shell seller-banner-inner"><div><p className="eyebrow text-[#f5b700]">FOR CAMPUS ENTREPRENEURS</p><h2>Turn what you sell<br/>into a business.</h2><p>Open your ESUT Marketplace store, manage your listings and reach customers who are ready to discover more.</p><Link href="/sell"><Button className="mt-6 bg-[#e31b23] hover:bg-[#c9161d]">Become a seller <ArrowRight size={17}/></Button></Link></div><Store className="seller-store-icon" size={180}/></div></section></main>
  <footer className="footer"><div className="page-shell grid gap-8 py-12 md:grid-cols-[1.5fr_1fr_1fr_1fr]"><div><div className="flex items-center gap-2"><img src={logo} alt="" className="h-12 w-12"/><strong className="text-lg">ESUT Marketplace</strong></div><p className="mt-4 max-w-xs text-sm leading-6 text-emerald-100/75">Built for the ESUT community. Open to customers everywhere.</p></div><div><b>Marketplace</b><Link href="/explore">Browse products</Link><Link href="/sell">Sell on ESUT</Link></div><div><b>Buyers</b><Link href="/account/orders">Orders</Link><Link href="/account/favorites">Favorites</Link></div><div><b>Trust & safety</b><Link href="/account/verification">Verification</Link><Link href="/sell">Seller requirements</Link></div></div><div className="border-t border-white/10"><div className="page-shell py-5 text-xs text-emerald-100/60">© 2026 ESUT Marketplace. Buy. Sell. Connect. Right from ESUT.</div></div></footer></div>;
}
