import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { MarketplaceProductGridSkeleton, StorefrontEmptyState, StorefrontFooter, StorefrontHeader, StorefrontProductCard, TrustBadge } from "@/components/StorefrontComponents";
import { trpc } from "@/lib/trpc";
import { ArrowRight, BadgeCheck, ShieldCheck, ShoppingCart, Sparkles, Store } from "lucide-react";
import { Link } from "wouter";

const categoryIcons: Record<string, string> = { Electronics: "⌁", Fashion: "✦", "Phones & Accessories": "◉", Books: "▤", "Hostel & Lodge": "⌂", "Food & Groceries": "◒", Services: "⌘", Computing: "⌗" };

function ProductSection({ eyebrow, title, rows, empty, loading = false, accent = "#00843d", treatment = "standard" }: { eyebrow: string; title: string; rows: any[]; empty: string; loading?: boolean; accent?: string; treatment?: "standard" | "deal" | "trending" | "campus" | "services" }) { const style = treatment === "deal" ? "border-[#f5b700]/35 bg-[#fffaf0]" : treatment === "trending" ? "border-[#08243b]/15 bg-[#f2f6fa]" : treatment === "campus" ? "border-[#00843d]/20 bg-[#f4fbf6]" : treatment === "services" ? "border-[#e31b23]/15 bg-[#fff8f8]" : "border-slate-200 bg-white"; const label = treatment === "deal" ? "Price-drop collection" : treatment === "trending" ? "Most viewed collection" : treatment === "campus" ? "Campus essentials collection" : treatment === "services" ? "Campus services collection" : "Latest marketplace collection"; return <section className="page-shell py-7"><div className={`rounded-[1.75rem] border p-5 sm:p-7 ${style}`} aria-label={label}><div className="section-head"><div><p className="eyebrow" style={{ color: accent }}>{eyebrow}</p><h2>{title}</h2></div><Link href="/explore" className="view-link">View all <ArrowRight size={16}/></Link></div>{loading ? <MarketplaceProductGridSkeleton /> : rows.length ? <div className="product-grid">{rows.slice(0, 8).map(row => <StorefrontProductCard key={row.listing.id} row={row}/>)}</div> : <StorefrontEmptyState>{empty}</StorefrontEmptyState>}</div></section>; }

export default function Home() {
  const home = trpc.marketplace.home.useQuery();
  const data = home.data; const fresh = data?.listings ?? []; const deals = data?.todayDeals ?? []; const trending = data?.trending ?? []; const campusPicks = data?.campusPicks ?? []; const services = data?.services ?? [];
  return <div className="min-h-screen bg-[#f7f9fc]"><StorefrontHeader categories={data?.categories ?? []}/>
  <main><section className="page-shell py-6"><div className="hero-grid"><div className="hero-copy"><p className="eyebrow"><Sparkles size={15}/> ESUT CAMPUS MARKETPLACE</p><h1>Everything you need.<br/><span>Right around you.</span></h1><p>Discover products, services and trusted sellers from ESUT and beyond. Shop campus deals with confidence.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/explore"><Button size="lg" className="bg-[#e31b23] hover:bg-[#c9161d]">Shop now <ArrowRight size={18}/></Button></Link><Link href="/sell"><Button size="lg" variant="outline" className="border-[#00843d] text-[#006b32]">Start selling</Button></Link></div><div className="mt-10 flex gap-7"><div><strong>Campus pickup</strong><span>Easy collection</span></div><div><strong>Verified sellers</strong><span>Shop smarter</span></div></div></div><div className="hero-art"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="hero-cart"><ShoppingCart size={74}/></div><div className="float-card float-phone">◉<span>Phones</span></div><div className="float-card float-books">▤<span>Books</span></div><div className="float-card float-fashion">✦<span>Fashion</span></div><p className="art-caption">Campus<br/><b>Deals</b></p></div></div></section>
  <section className="page-shell py-6"><div className="section-head"><div><p className="eyebrow text-[#00843d]">DISCOVER MORE</p><h2>Shop by category</h2></div><Link href="/explore" className="view-link">View all <ArrowRight size={16}/></Link></div><div className="category-row" aria-busy={home.isLoading}>{home.isLoading ? Array.from({ length: 8 }, (_, index) => <div aria-hidden="true" className="category-tile" key={index}><div className="h-7 w-7 animate-pulse rounded-md bg-slate-200 motion-reduce:animate-none"/><div className="mt-2 h-4 w-4/5 animate-pulse rounded bg-slate-200 motion-reduce:animate-none"/><div className="mt-2 h-3 w-2/5 animate-pulse rounded bg-slate-200 motion-reduce:animate-none"/></div>) : (data?.categories ?? []).slice(0, 8).map(category => <Link href={`/category/${category.slug}`} key={category.id} className="category-tile"><span>{categoryIcons[category.name] ?? "◇"}</span><b>{category.name}</b><small>Explore now</small></Link>)}</div></section>
  <section className="deals-strip"><div className="page-shell flex flex-col gap-5 py-7 sm:flex-row sm:items-center sm:justify-between"><div><p className="eyebrow text-[#f5b700]">TODAY'S DEALS</p><h2>Price drops from active campus sellers.</h2></div><Link href="/explore"><Button className="bg-white text-[#111827] hover:bg-slate-100">Browse all listings <ArrowRight size={17}/></Button></Link></div></section>
  {home.isError ? <div className="page-shell py-12" role="alert"><div className="rounded-2xl bg-[#fff3f3] p-8 text-center text-[#b91c1c] ring-1 ring-[#fecaca]"><h2 className="text-xl font-extrabold">We could not load marketplace collections</h2><p className="mt-2 text-sm">Try again to retrieve the latest real listings, stores, and categories.</p><Button variant="outline" className="mt-4" onClick={() => home.refetch()}>Try again</Button></div></div> : <><ProductSection eyebrow="JUST IN" title="Fresh arrivals" rows={fresh} loading={home.isLoading} empty="Listings will appear here as approved sellers publish them." accent="#e31b23"/><ProductSection eyebrow="SAVINGS" title="Today's Deals" rows={deals} loading={home.isLoading} empty="No active price-drop listings are available today." accent="#b77900" treatment="deal"/><ProductSection eyebrow="POPULAR NOW" title="Trending on campus" rows={trending} loading={home.isLoading} empty="Trending listings will appear once the marketplace receives more activity." accent="#08243b" treatment="trending"/><ProductSection eyebrow="STUDENT ESSENTIALS" title="Campus Picks" rows={campusPicks} loading={home.isLoading} empty="Campus-relevant listings will appear as sellers publish them." accent="#00843d" treatment="campus"/>
  <section className="page-shell py-9"><div className="section-head"><div><p className="eyebrow text-[#00843d]">TRUSTED STORES</p><h2>Verified Sellers</h2></div><Link href="/explore" className="view-link">Browse listings <ArrowRight size={16}/></Link></div>{home.isLoading ? <div aria-busy="true" className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{Array.from({ length: 3 }, (_, index) => <div key={index} className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div className="h-11 w-11 animate-pulse rounded-xl bg-slate-200 motion-reduce:animate-none"/><div className="mt-5 h-5 w-3/5 animate-pulse rounded bg-slate-200 motion-reduce:animate-none"/><div className="mt-3 h-3 w-2/5 animate-pulse rounded bg-slate-200 motion-reduce:animate-none"/></div>)}</div> : data?.stores.length ? <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{data.stores.map(store => <article key={store.id} className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div className="flex items-start gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#eaf7ef] text-[#00843d]"><Store size={21}/></span><div><h3 className="font-extrabold">{store.name}</h3><p className="mt-1 text-xs text-slate-500">{store.location}</p></div></div><p className="mt-5"><TrustBadge/></p><Link href="/explore" className="mt-5 inline-block text-sm font-bold text-[#00843d]">Explore marketplace <ArrowRight className="inline" size={14}/></Link></article>)}</div> : <StorefrontEmptyState icon={<Store size={34}/>}>Verified stores will appear after administrators approve their applications.</StorefrontEmptyState>}</section>
  <section className="page-shell py-9"><div className="section-head"><div><p className="eyebrow text-[#e31b23]">PICKUP PROVEN</p><h2>Popular Stores</h2></div><Link href="/explore" className="view-link">Browse listings <ArrowRight size={16}/></Link></div>{home.isLoading ? <div aria-busy="true" className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{Array.from({ length: 3 }, (_, index) => <div key={index} className="rounded-2xl border border-slate-200 bg-white p-6"><div className="h-6 w-6 animate-pulse rounded bg-slate-200 motion-reduce:animate-none"/><div className="mt-5 h-5 w-3/5 animate-pulse rounded bg-slate-200 motion-reduce:animate-none"/><div className="mt-3 h-3 w-2/5 animate-pulse rounded bg-slate-200 motion-reduce:animate-none"/></div>)}</div> : data?.popularStores.length ? <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{data.popularStores.map(store => <article key={store.id} className="rounded-2xl border border-[#e31b23]/10 bg-[#fffafa] p-6"><Store className="text-[#e31b23]"/><h3 className="mt-4 font-extrabold">{store.name}</h3><p className="mt-1 text-sm text-slate-600">{store.location}</p><p className="mt-4 text-sm font-bold text-[#006b32]">{store.completedOrderCount ? `${store.completedOrderCount} completed pickup${store.completedOrderCount === 1 ? "" : "s"}` : "New verified store"}</p></article>)}</div> : <StorefrontEmptyState icon={<Store size={34}/>}>Popular stores will appear as campus pickups are completed.</StorefrontEmptyState>}</section>
  <ProductSection eyebrow="CAMPUS SERVICES" title="Book a campus service" rows={services} loading={home.isLoading} empty="Service listings will appear here when approved sellers publish them." accent="#e31b23" treatment="services"/></>}
  <section className="page-shell py-8"><div className="trust-grid"><div><span className="trust-icon"><ShieldCheck/></span><h2>Why ESUT Marketplace</h2><p>Find verified sellers, complete a protected campus-pickup order, and keep your marketplace communication inside your account.</p><Link href="/explore" className="view-link">Explore verified listings <ArrowRight size={16}/></Link></div><div className="trust-points"><p><BadgeCheck/> ESUT community marketplace</p><p><BadgeCheck/> Seller verification workflow</p><p><BadgeCheck/> Secure account architecture</p><p><BadgeCheck/> Campus pickup and cash-on-pickup</p></div></div></section>
  <section className="seller-banner"><div className="page-shell seller-banner-inner"><div><p className="eyebrow text-[#f5b700]">FOR CAMPUS ENTREPRENEURS</p><h2>Turn what you sell<br/>into a business.</h2><p>Open your ESUT Marketplace store, manage your listings and reach customers who are ready to discover more.</p><Link href="/sell"><Button className="mt-6 bg-[#e31b23] hover:bg-[#c9161d]">Become a seller <ArrowRight size={17}/></Button></Link></div><Store className="seller-store-icon" size={180}/></div></section></main>
  <StorefrontFooter/></div>;
}
