import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, Mail, ShieldCheck } from "lucide-react";
import { FormEvent, useState } from "react";
import { Link, useLocation } from "wouter";
import { toast } from "sonner";
import { useEffect } from "react";

const Shell = ({ children }: { children: React.ReactNode }) => <main className="min-h-screen bg-[#eef8ff] px-4 py-12"><section className="mx-auto w-full max-w-[560px] rounded-[28px] bg-white px-7 py-9 shadow-[0_24px_60px_rgba(29,78,216,.12)] sm:px-14"><Link href="/login" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-600 hover:text-[#00843d]"><ArrowLeft size={20}/> Back to login</Link><div className="mt-8 text-center"><img src="/manus-storage/esut-main-logo_0f99c6ab.png" alt="ESUT Marketplace" className="mx-auto h-14 w-14 object-contain"/>{children}</div></section></main>;
export function ForgotPasswordPage(){const [email,setEmail]=useState("");const availability=trpc.auth.passwordResetAvailability.useQuery();const [deliveryAvailable,setDeliveryAvailable]=useState<boolean|null>(null);const request=trpc.auth.requestPasswordReset.useMutation({onSuccess:data=>{setDeliveryAvailable(data.passwordResetEmailAvailable);if(data.passwordResetEmailAvailable)toast.success("If an account exists, a reset email has been sent.");},onError:e=>toast.error(e.message)});const submit=(event:FormEvent)=>{event.preventDefault();request.mutate({email})};const unavailable=deliveryAvailable===false||availability.data?.passwordResetEmailAvailable===false;return <Shell><h1 className="mt-5 text-3xl font-extrabold">Password reset</h1>{availability.isLoading?<p className="mt-5 text-slate-500">Checking password-recovery availability…</p>:availability.isError?<div role="alert" className="mt-6 rounded-xl bg-[#fff3f3] p-4 text-left text-sm text-[#b91c1c] ring-1 ring-[#fecaca]"><strong>We could not check password-recovery availability.</strong><p className="mt-2">Try again before requesting a reset link. Normal-recipient delivery remains subject to the configured provider boundary.</p><Button variant="outline" className="mt-3" onClick={() => availability.refetch()}>Try again</Button></div>:unavailable?<div className="mt-6 rounded-xl bg-amber-50 p-4 text-left text-sm leading-6 text-amber-900"><strong>Password-recovery email is temporarily unavailable.</strong><p className="mt-2">ESUT Marketplace is not currently able to deliver reset links to ordinary email addresses. Please use the official marketplace support channel for account-recovery assistance.</p><Link href="/login" className="mt-3 inline-block font-bold text-[#00843d] hover:underline">Return to login</Link></div>:<><p className="mt-3 text-slate-500">Enter your email and we’ll send a one-hour reset link if a matching account exists.</p><form className="mt-8 space-y-5 text-left" onSubmit={submit}><div className="space-y-2"><Label htmlFor="resetEmail">Email address</Label><div className="relative"><Mail className="absolute left-3 top-3.5 text-slate-400" size={18}/><Input id="resetEmail" required type="email" value={email} onChange={event=>setEmail(event.target.value)} placeholder="someone@example.com" className="h-12 pl-10"/></div></div><Button disabled={request.isPending} className="h-12 w-full bg-[#e31b23] hover:bg-[#c9161d]">Send reset link</Button></form></>}</Shell>}
export function ResetPasswordPage(){const [location,navigate]=useLocation();const token=new URLSearchParams(location.split("?")[1]??"").get("token")??"";const [password,setPassword]=useState("");const [confirm,setConfirm]=useState("");const reset=trpc.auth.resetPassword.useMutation({onSuccess:()=>{toast.success("Password reset successfully.");navigate("/account")},onError:e=>toast.error(e.message)});const submit=(event:FormEvent)=>{event.preventDefault();if(password!==confirm)return toast.error("Passwords do not match.");reset.mutate({token,password})};return <Shell><h1 className="mt-5 text-3xl font-extrabold">Choose a new password</h1><p className="mt-3 text-slate-500">Use at least 10 characters. This reset link expires after one hour.</p>{!token?<p className="mt-8 rounded-xl bg-red-50 p-4 text-sm text-red-700">This reset link is missing its token. Request a new link.</p>:<form className="mt-8 space-y-5 text-left" onSubmit={submit}><div className="space-y-2"><Label htmlFor="newPassword">New password</Label><Input id="newPassword" required minLength={10} type="password" value={password} onChange={event=>setPassword(event.target.value)} className="h-12"/></div><div className="space-y-2"><Label htmlFor="confirmPassword">Confirm password</Label><Input id="confirmPassword" required minLength={10} type="password" value={confirm} onChange={event=>setConfirm(event.target.value)} className="h-12"/></div><Button disabled={reset.isPending} className="h-12 w-full bg-[#e31b23] hover:bg-[#c9161d]">Reset password</Button></form>}</Shell>}
export function VerifyEmailPage(){const [location]=useLocation();const token=new URLSearchParams(location.split("?")[1]??"").get("token")??"";const verify=trpc.auth.verifyEmail.useMutation({onSuccess:()=>toast.success("Your email is verified."),onError:e=>toast.error(e.message)});useEffect(()=>{if(token&&!verify.isPending&&!verify.isSuccess)verify.mutate({token})},[token]);return <Shell><ShieldCheck className="mx-auto mt-5 text-[#00843d]" size={40}/><h1 className="mt-4 text-3xl font-extrabold">Verify your email</h1><p className="mt-3 text-slate-500">{token ? verify.isPending ? "Verifying your email…" : verify.isSuccess ? "Your email has been verified. You can continue to your account." : "This verification link is invalid or has expired." : "Check your inbox for a verification link. It expires after one hour."}</p><Link href="/account"><Button className="mt-7 bg-[#00843d] hover:bg-[#006b32]">Open my account</Button></Link></Shell>}
