import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { condition, naira } from "@/lib/marketplace";
import { ArrowLeft, CheckCircle2, Heart, MapPin, MessageCircle, Minus, Package, Plus, ShieldCheck, ShoppingCart, Store } from "lucide-react";
import { Link, useLocation, useRoute } from "wouter";
import { useState } from "react";
import { toast } from "sonner";

export default function ProductPage() {
  const [, params] = useRoute("/product/:slug"); const [, navigate] = useLocation();
  const { isAuthenticated } = useAuth(); const [quantity, setQuantity] = useState(1); const [offerOpen, setOfferOpen] = useState(false); const [messageOpen, setMessageOpen] = useState(false); const [offerAmount, setOfferAmount] = useState(""); const [offerMessage, setOfferMessage] = useState(""); const [messageBody, setMessageBody] = useState("");
  const product = trpc.marketplace.product.useQuery({ slug: params?.slug ?? "" }, { enabled: Boolean(params?.slug) });
  const add = trpc.cart.add.useMutation({ onSuccess: () => { toast.success("Added to your cart"); navigate("/cart"); }, onError: err => toast.error(err.message) });
  const favorite = trpc.favorites.toggle.useMutation({ onSuccess: data => toast.success(data.favorited ? "Saved to favorites" : "Removed from favorites"), onError: () => toast.error("Please sign in to save products") });
  const offer = trpc.offers.create.useMutation({ onSuccess: () => { toast.success("Your offer was sent to the seller."); setOfferOpen(false); setOfferAmount(""); setOfferMessage(""); }, onError: error => toast.error(error.message) });
  const startMessage = trpc.messaging.start.useMutation({ onSuccess: data => { toast.success("Conversation started."); navigate(`/account/messages/${data.conversationId}`); }, onError: error => toast.error(error.message) });
  if (product.isLoading) return <div className="page-shell py-16">Loading this listing…</div>;
  if (!product.data) return <div className="page-shell py-16">This listing is unavailable.</div>;
  const { listing, store, category, images } = product.data; const image = images[0]?.url;
  const requestOffer = () => { if (isAuthenticated) setOfferOpen(value => !value); else toast.error("Sign in to make an offer"); };
  const requestMessage = () => { if (isAuthenticated) setMessageOpen(value => !value); else toast.error("Sign in to message the seller"); };
  return <div className="min-h-screen bg-[#f7f9fc]"><main className="page-shell py-7"><Link href="/" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-600 hover:text-[#00843d]"><ArrowLeft size={16}/> Back to marketplace</Link><div className="mt-6 grid gap-7 lg:grid-cols-[1.12fr_.88fr]">
    <section className="overflow-hidden rounded-[1.75rem] bg-white shadow-sm ring-1 ring-slate-200"><div className="product-visual min-h-[420px]">{image ? <img src={image} alt={listing.title} className="h-full w-full object-cover" /> : <Package size={110} strokeWidth={1.15}/>}</div><div className="grid grid-cols-4 gap-3 p-4">{[0, 1, 2, 3].map(index => <div key={index} className="product-visual h-20 rounded-xl text-slate-400">{image && index === 0 ? <img src={image} alt="" className="h-full w-full object-cover"/> : <Package size={24}/>}</div>)}</div></section>
    <section><div className="flex items-start justify-between gap-4"><div><p className="mb-2 text-sm font-bold uppercase tracking-[.14em] text-[#00843d]">{category.name}</p><h1 className="text-3xl font-extrabold leading-tight text-[#111827]">{listing.title}</h1></div><Button variant="outline" size="icon" onClick={() => favorite.mutate({ listingId: listing.id })}><Heart size={19}/></Button></div><div className="mt-5 flex items-center gap-3"><span className="text-3xl font-black text-[#e31b23]">{naira(listing.priceKobo)}</span>{listing.compareAtPriceKobo && <span className="text-base text-slate-400 line-through">{naira(listing.compareAtPriceKobo)}</span>}</div><div className="mt-5 flex flex-wrap gap-2"><span className="tag tag-green"><CheckCircle2 size={14}/> Available</span><span className="tag">{condition(listing.condition)}</span><span className="tag"><MapPin size={14}/>{listing.location}</span></div><div className="my-6 border-t border-slate-200"/><p className="leading-7 text-slate-600">{listing.description}</p><div className="mt-6 flex items-center gap-4"><div className="flex h-11 items-center rounded-xl border border-slate-200 bg-white"><button type="button" className="p-3" onClick={() => setQuantity(q => Math.max(1, q - 1))}><Minus size={16}/></button><span className="w-8 text-center font-bold">{quantity}</span><button type="button" className="p-3" onClick={() => setQuantity(q => q + 1)}><Plus size={16}/></button></div><Button className="flex-1 bg-[#e31b23] hover:bg-[#c9161d]" disabled={add.isPending} onClick={() => isAuthenticated ? add.mutate({ listingId: listing.id, quantity }) : toast.error("Sign in to add this item")}><ShoppingCart size={18}/> Add to cart</Button></div>
    {listing.allowOffers && <Button variant="outline" className="mt-3 w-full border-[#00843d] text-[#006b32] hover:bg-[#00843d]/5" onClick={requestOffer}>Make an offer</Button>}
    {offerOpen && <form onSubmit={event => { event.preventDefault(); const amountKobo = Math.round(Number(offerAmount) * 100); if (!Number.isFinite(amountKobo) || amountKobo <= 0) { toast.error("Enter a valid Naira amount."); return; } offer.mutate({ listingId: listing.id, amountKobo, quantity, message: offerMessage || undefined }); }} className="mt-3 rounded-2xl border border-[#f5b700]/40 bg-[#fff7e6] p-4"><p className="font-bold">Make an offer for {quantity} item(s)</p><input type="number" min="1" step="0.01" value={offerAmount} onChange={event => setOfferAmount(event.target.value)} className="mt-3 w-full rounded-xl border bg-white p-3" placeholder="Offer amount in ₦" /><textarea value={offerMessage} onChange={event => setOfferMessage(event.target.value)} className="mt-3 min-h-20 w-full rounded-xl border bg-white p-3" placeholder="Optional note to the seller" /><Button type="submit" className="mt-3 bg-[#00843d]" disabled={offer.isPending}>Send offer</Button></form>}
    <div className="mt-7 rounded-2xl border border-[#00843d]/15 bg-[#00843d]/5 p-5"><div className="flex gap-4"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-[#00843d] text-white"><Store size={19}/></span><div className="min-w-0 flex-1"><p className="font-bold text-[#111827]">{store.name} {store.isVerified && <ShieldCheck className="ml-1 inline text-[#00843d]" size={16}/>}</p><p className="mt-1 text-sm text-slate-600">{store.isVerified ? "Verified seller" : "Seller"} · {store.location}</p><div className="mt-3 flex flex-wrap gap-3"><Link href={`/store/${store.slug}`} className="text-sm font-bold text-[#00843d]">Visit store</Link><button type="button" className="inline-flex items-center gap-1 text-sm font-bold text-[#00843d]" onClick={requestMessage}><MessageCircle size={15}/> Message seller</button></div>{messageOpen && <form onSubmit={event => { event.preventDefault(); if (!messageBody.trim()) { toast.error("Write a message for the seller."); return; } startMessage.mutate({ listingId: listing.id, body: messageBody }); }} className="mt-4"><textarea value={messageBody} onChange={event => setMessageBody(event.target.value)} className="min-h-20 w-full rounded-xl border bg-white p-3" placeholder="Ask the seller a product question" /><Button type="submit" size="sm" className="mt-2 bg-[#00843d]" disabled={startMessage.isPending}>Start conversation</Button></form>}</div></div></div>
    </section></div></main></div>;
}
