import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { condition, naira } from "@/lib/marketplace";
import { addGuestCartLine } from "@/lib/guestCart";
import { ArrowLeft, Bell, CheckCircle2, ChevronDown, Flag, Headphones, Heart, MapPin, MessageCircle, Minus, Package, Plus, ShieldCheck, ShoppingCart, Store } from "lucide-react";
import { Link, useLocation, useRoute } from "wouter";
import { useState } from "react";
import { toast } from "sonner";

export default function ProductPage() {
  const [, params] = useRoute("/product/:slug");
  const [, navigate] = useLocation();
  const { isAuthenticated } = useAuth();
  const [quantity, setQuantity] = useState(1);
  const [activeImageIndex, setActiveImageIndex] = useState(0);
  const [offerOpen, setOfferOpen] = useState(false);
  const [messageOpen, setMessageOpen] = useState(false);
  const [reportOpen, setReportOpen] = useState(false);
  const [offerAmount, setOfferAmount] = useState("");
  const [offerMessage, setOfferMessage] = useState("");
  const [messageBody, setMessageBody] = useState("");
  const [reportReason, setReportReason] = useState("");
  const [reportDetails, setReportDetails] = useState("");
  const [openFaq, setOpenFaq] = useState<string | null>(null);
  const [reminderOpen, setReminderOpen] = useState(false);
  const [reminderType, setReminderType] = useState<"TOMORROW" | "THREE_DAYS" | "ONE_WEEK" | "CUSTOM">("TOMORROW");
  const [reminderAt, setReminderAt] = useState("");
  const [reminderNote, setReminderNote] = useState("");
  const product = trpc.marketplace.product.useQuery({ slug: params?.slug ?? "" }, { enabled: Boolean(params?.slug) });
  const reminderStatus = trpc.reminders.forListing.useQuery({ listingId: product.data?.listing.id ?? 0 }, { enabled: Boolean(isAuthenticated && product.data?.listing.id) });
  const utils = trpc.useUtils();
  const add = trpc.cart.add.useMutation({ onSuccess: () => { toast.success("Added to your cart"); navigate("/cart"); }, onError: err => toast.error(err.message) });
  const buyNow = trpc.cart.add.useMutation({ onSuccess: () => { toast.success("Item added. Review your pickup order before placing it."); navigate("/checkout"); }, onError: err => toast.error(err.message) });
  const favorite = trpc.favorites.toggle.useMutation({ onSuccess: data => toast.success(data.favorited ? "Saved to favorites" : "Removed from favorites"), onError: () => toast.error("Please sign in to save products") });
  const offer = trpc.offers.create.useMutation({ onSuccess: () => { toast.success("Your offer was sent to the seller."); setOfferOpen(false); setOfferAmount(""); setOfferMessage(""); }, onError: error => toast.error(error.message) });
  const startMessage = trpc.messaging.start.useMutation({ onSuccess: data => { toast.success("Conversation started."); navigate(`/account/messages/${data.conversationId}`); }, onError: error => toast.error(error.message) });
  const report = trpc.support.report.useMutation({ onSuccess: () => { toast.success("Your report was submitted for administrator review."); setReportOpen(false); setReportReason(""); setReportDetails(""); }, onError: error => toast.error(error.message) });
  const createReminder = trpc.reminders.create.useMutation({ onSuccess: () => { toast.success("Reminder set. We will notify you in your account when it is due."); setReminderOpen(false); setReminderNote(""); setReminderAt(""); void utils.reminders.forListing.invalidate(); void utils.reminders.listMine.invalidate(); }, onError: error => toast.error(error.message) });

  if (product.isLoading) return <main className="page-shell py-16"><div className="h-8 w-48 animate-pulse rounded bg-slate-200" /><div className="mt-6 grid gap-7 lg:grid-cols-2"><div className="aspect-square animate-pulse rounded-[1.75rem] bg-slate-200" /><div className="space-y-4"><div className="h-10 animate-pulse rounded bg-slate-200" /><div className="h-24 animate-pulse rounded bg-slate-200" /><div className="h-48 animate-pulse rounded bg-slate-200" /></div></div></main>;
  if (product.isError) return <main className="page-shell py-16"><div role="alert" className="rounded-[1.75rem] bg-[#fff3f3] p-8 text-center text-[#b91c1c] ring-1 ring-[#fecaca]"><h1 className="text-xl font-extrabold">We could not load this listing</h1><p className="mt-2 text-sm">Try again to retrieve the latest product, seller, and review details.</p><Button variant="outline" className="mt-4" onClick={() => product.refetch()}>Try again</Button></div></main>;
  if (!product.data) return <main className="page-shell py-16 text-center"><Package className="mx-auto text-slate-300" size={64} strokeWidth={1.2} /><h1 className="mt-5 text-2xl font-extrabold">This listing is unavailable</h1><p className="mt-2 text-slate-600">It may have been removed, sold, or is no longer published.</p><Link href="/explore"><Button className="mt-6 bg-[#e31b23]">Explore more listings</Button></Link></main>;

  const { listing, store, category, images, productReviews, reviewSummary, availability, evidenceVideo } = product.data;
  const activeImage = images[activeImageIndex] ?? images[0];
  const categoryName = category.name.toLowerCase();
  const fallbackLabel = categoryName.includes("elect") || categoryName.includes("phone") || categoryName.includes("comput") ? "Campus tech listing" : categoryName.includes("fashion") ? "Campus fashion listing" : "Campus marketplace listing"; const awaitingStock = availability.status === "AWAITING_STOCK"; const availabilityLabel = awaitingStock ? "Awaiting stock" : availability.status === "LOW_STOCK" ? `${availability.availableUnits} left — low stock` : `${availability.availableUnits} in stock`;
  const requestOffer = () => { if (isAuthenticated) setOfferOpen(value => !value); else toast.error("Sign in to make an offer"); };
  const requestMessage = () => { if (isAuthenticated) setMessageOpen(value => !value); else toast.error("Sign in to message the seller"); };
  const addToCart = () => {
    if (isAuthenticated) add.mutate({ listingId: listing.id, quantity });
    else { addGuestCartLine({ listingId: listing.id, title: listing.title, priceKobo: listing.priceKobo, quantity, imageUrl: activeImage?.url }); toast.success("Saved in your guest cart. Sign in before checkout."); navigate("/cart"); }
  };
  const buy = () => { if (!isAuthenticated) { toast.error("Sign in to review and place a pickup order."); navigate("/login"); return; } buyNow.mutate({ listingId: listing.id, quantity }); };
  const mutationPending = add.isPending || buyNow.isPending;
  const trustItems = [
    { icon: <ShieldCheck size={18} />, title: store.isVerified ? "Verified seller" : "Seller profile", body: store.isVerified ? "Reviewed by ESUT Marketplace." : "Seller information is shown before you buy." },
    { icon: <MapPin size={18} />, title: "Campus pickup", body: "Arrange collection with the seller after confirmation." },
    { icon: <CheckCircle2 size={18} />, title: "Server-checked stock", body: "Price and availability are rechecked at checkout." },
  ];
  const faqItems = [
    ["How does campus pickup work?", "After your order is confirmed, arrange a safe ESUT campus collection point with the seller."],
    ["When do I pay?", "This marketplace supports cash on pickup. Pay the seller only when you collect the item."],
    ["Can I make an offer?", listing.allowOffers ? "Yes. Choose Make an offer and send the seller your Naira amount and optional note." : "This listing is not currently accepting offers."],
  ];

  return <div className="min-h-screen bg-[#f7f9fc] pb-24 lg:pb-0"><main className="page-shell py-6 sm:py-8">
    <Link href="/explore" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-600 transition hover:text-[#00843d]"><ArrowLeft size={16} /> Back to marketplace</Link>
    <div className="mt-5 grid gap-8 lg:grid-cols-[1.08fr_.92fr] lg:items-start">
      <section aria-label="Product image gallery" className="min-w-0">
        <div className="overflow-hidden rounded-[1.75rem] bg-white shadow-sm ring-1 ring-slate-200"><div className="product-visual aspect-square min-h-[320px] sm:min-h-[500px]">{activeImage?.url ? <img src={activeImage.url} alt={activeImage.altText || listing.title} className="h-full w-full object-cover" /> : <div className="relative flex h-full flex-col items-center justify-center overflow-hidden bg-[radial-gradient(circle_at_50%_40%,#eaf7ef_0%,#f4f8f5_44%,#fff7e6_100%)] text-center text-[#006b32]"><div className="absolute -right-16 -top-16 h-48 w-48 rounded-full border-[22px] border-[#00843d]/10" /><div className="absolute -bottom-20 -left-16 h-48 w-48 rounded-full border-[22px] border-[#e31b23]/10" /><span className="relative flex h-24 w-24 items-center justify-center rounded-3xl bg-white text-[#00843d] shadow-sm ring-1 ring-[#00843d]/15"><Headphones size={54} strokeWidth={1.25} /></span><p className="relative mt-5 text-xs font-black uppercase tracking-[.18em] text-[#00843d]">{fallbackLabel}</p><p className="relative mt-2 text-lg font-extrabold text-[#111827]">No seller photo yet</p><p className="relative mt-1 max-w-xs px-5 text-sm text-slate-500">The listing is real and available for safe ESUT campus pickup.</p></div>}</div>{images.length > 0 && <div className="flex gap-3 overflow-x-auto border-t border-slate-100 p-4">{images.map((item, index) => <button type="button" key={item.id} aria-label={`View image ${index + 1}`} aria-pressed={activeImage?.id === item.id} onClick={() => setActiveImageIndex(index)} className={`product-visual h-20 w-20 shrink-0 overflow-hidden rounded-xl border-2 transition focus:outline-none focus:ring-2 focus:ring-[#00843d] ${activeImage?.id === item.id ? "border-[#e31b23]" : "border-transparent"}`}><img src={item.url} alt={item.altText || `${listing.title} view ${index + 1}`} className="h-full w-full object-cover" /></button>)}</div>}</div>
        {evidenceVideo ? <section className="mt-5 overflow-hidden rounded-2xl bg-white p-4 ring-1 ring-[#00843d]/20"><div className="mb-3 flex items-center gap-2 text-sm font-extrabold text-[#006b32]"><CheckCircle2 size={17}/>Seller evidence video reviewed</div><video controls preload="metadata" className="aspect-video w-full rounded-xl bg-black" src={evidenceVideo.url}>Your browser cannot play this reviewed seller video.</video></section> : null}<div className="mt-5 hidden gap-3 sm:grid sm:grid-cols-3">{trustItems.map(item => <div key={item.title} className="rounded-2xl bg-white p-4 ring-1 ring-slate-200"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-[#eaf7ef] text-[#00843d]">{item.icon}</span><p className="mt-3 text-sm font-extrabold">{item.title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{item.body}</p></div>)}</div>
      </section>
      <section className="min-w-0 lg:sticky lg:top-5"><div className="flex items-start justify-between gap-4"><div><p className="mb-3 text-xs font-black uppercase tracking-[.16em] text-[#00843d]">{category.name}</p><h1 className="text-3xl font-black leading-[1.08] tracking-tight text-[#111827] sm:text-5xl">{listing.title}</h1></div><Button aria-label="Save listing to favorites" variant="outline" size="icon" className="shrink-0 rounded-full" onClick={() => favorite.mutate({ listingId: listing.id })}><Heart size={19} /></Button></div>
        <div className="mt-5 flex flex-wrap items-end gap-x-4 gap-y-2"><span className="text-3xl font-black text-[#e31b23] sm:text-4xl">{naira(listing.priceKobo)}</span>{listing.compareAtPriceKobo && <span className="text-base text-slate-400 line-through">{naira(listing.compareAtPriceKobo)}</span>}{listing.compareAtPriceKobo && listing.compareAtPriceKobo > listing.priceKobo && <span className="rounded-lg bg-[#eaf7ef] px-2.5 py-1 text-xs font-black text-[#006b32]">Save {naira(listing.compareAtPriceKobo - listing.priceKobo)}</span>}</div>
        <div className="mt-4 flex flex-wrap items-center gap-3"><span className="font-bold text-[#8a6500]">{reviewSummary.count ? `${reviewSummary.averageRating?.toFixed(1)} ★` : "No reviews yet"}</span>{reviewSummary.count ? <Link href="#reviews" className="text-sm text-slate-500 underline-offset-4 hover:underline">{reviewSummary.count} verified purchase review{reviewSummary.count === 1 ? "" : "s"}</Link> : <span className="text-sm text-slate-500">Be the first verified buyer to review this listing.</span>}</div>
        <div className="mt-5 flex flex-wrap gap-2"><span className={`tag ${awaitingStock ? "bg-slate-100 text-slate-700" : availability.status === "LOW_STOCK" ? "bg-[#fff3c4] text-[#7a5700]" : "tag-green"}`}><CheckCircle2 size={14} /> {availabilityLabel}</span><span className="tag">{condition(listing.condition)}</span><span className="tag"><MapPin size={14} />{listing.location}</span></div>
        <p className="mt-6 text-base leading-7 text-slate-600">{listing.description}</p>
        <div className="mt-6 rounded-2xl border border-[#00843d]/15 bg-[#eaf7ef] p-4"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 shrink-0 text-[#00843d]" size={20} /><div><p className="font-extrabold text-[#111827]">Safe ESUT purchase</p><p className="mt-1 text-sm leading-6 text-slate-600">Campus pickup and cash on pickup only. The server independently rechecks stock and price before an order is created.</p></div></div></div>
        <div className="mt-6 flex flex-wrap items-center gap-3"><div className="flex h-12 items-center rounded-xl border border-slate-200 bg-white"><button type="button" aria-label="Decrease quantity" disabled={awaitingStock} className="p-3 text-slate-600 hover:text-[#e31b23] disabled:opacity-40" onClick={() => setQuantity(q => Math.max(1, q - 1))}><Minus size={16} /></button><span className="w-9 text-center font-bold" aria-live="polite">{quantity}</span><button type="button" aria-label="Increase quantity" disabled={awaitingStock} className="p-3 text-slate-600 hover:text-[#00843d] disabled:opacity-40" onClick={() => setQuantity(q => q + 1)}><Plus size={16} /></button></div><Button className="min-h-12 min-w-40 flex-1 bg-[#e31b23] text-base font-extrabold hover:bg-[#c9161d] disabled:bg-slate-300" disabled={mutationPending || awaitingStock} onClick={addToCart}><ShoppingCart size={18} /> {awaitingStock ? "Awaiting restock" : add.isPending ? "Adding…" : "Add to cart"}</Button><Button variant="outline" className="min-h-12 min-w-32 border-[#00843d] text-base font-extrabold text-[#006b32] hover:bg-[#00843d]/5" disabled={mutationPending || awaitingStock} onClick={buy}>{awaitingStock ? "Awaiting stock" : buyNow.isPending ? "Preparing…" : "Buy now"}</Button></div>
        <div className="mt-3 flex flex-wrap gap-3"><Button variant="outline" className="flex-1" onClick={requestOffer}>Make an offer</Button><Button variant="outline" className="flex-1" onClick={requestMessage}><MessageCircle size={16} /> Message seller</Button><Button variant="outline" className="flex-1 border-[#f5b700] text-[#7a5700]" onClick={() => { if (!isAuthenticated) { toast.error("Sign in to set a product reminder."); navigate("/login"); return; } setReminderOpen(value => !value); }}><Bell size={16}/>{reminderStatus.data?.status === "ACTIVE" ? "Reminder set" : "Remind me"}</Button></div>
        {reminderOpen && <form onSubmit={event => { event.preventDefault(); if (!listing) return; if (reminderType === "CUSTOM" && !reminderAt) { toast.error("Choose a reminder date and time."); return; } createReminder.mutate({ listingId: listing.id, reminderType, scheduledFor: reminderType === "CUSTOM" ? new Date(reminderAt) : undefined, note: reminderNote || undefined }); }} className="mt-3 rounded-2xl border border-[#f5b700]/40 bg-[#fff7e6] p-4"><div className="flex items-start gap-3"><Bell className="mt-0.5 text-[#8a6500]" size={19}/><div><p className="font-extrabold">Don’t forget this one</p><p className="mt-1 text-sm text-slate-600">A reminder does not reserve this product. Availability and price are checked again when you return.</p></div></div><label className="mt-4 block text-sm font-bold">When should we remind you?<select value={reminderType} onChange={event => setReminderType(event.target.value as typeof reminderType)} className="mt-2 w-full rounded-xl border bg-white p-3"><option value="TOMORROW">Tomorrow</option><option value="THREE_DAYS">In 3 days</option><option value="ONE_WEEK">In 1 week</option><option value="CUSTOM">Choose date &amp; time</option></select></label>{reminderType === "CUSTOM" && <label className="mt-3 block text-sm font-bold">Date and time<input required type="datetime-local" value={reminderAt} onChange={event => setReminderAt(event.target.value)} className="mt-2 w-full rounded-xl border bg-white p-3" /></label>}<label className="mt-3 block text-sm font-bold">Optional note<input value={reminderNote} maxLength={500} onChange={event => setReminderNote(event.target.value)} className="mt-2 w-full rounded-xl border bg-white p-3" placeholder="Why are you reminding yourself?" /></label><div className="mt-4 flex gap-2"><Button type="submit" className="bg-[#00843d]" disabled={createReminder.isPending}>{createReminder.isPending ? "Saving…" : "Set reminder"}</Button><Button type="button" variant="outline" onClick={() => setReminderOpen(false)}>Cancel</Button></div></form>}
        {listing.allowOffers && offerOpen && <form onSubmit={event => { event.preventDefault(); const amountKobo = Math.round(Number(offerAmount) * 100); if (!Number.isFinite(amountKobo) || amountKobo <= 0) { toast.error("Enter a valid Naira amount."); return; } offer.mutate({ listingId: listing.id, amountKobo, quantity, message: offerMessage || undefined }); }} className="mt-3 rounded-2xl border border-[#f5b700]/40 bg-[#fff7e6] p-4"><p className="font-bold">Make an offer for {quantity} item(s)</p><input aria-label="Offer amount in Naira" type="number" min="1" step="0.01" value={offerAmount} onChange={event => setOfferAmount(event.target.value)} className="mt-3 w-full rounded-xl border bg-white p-3" placeholder="Offer amount in ₦" /><textarea aria-label="Offer note" value={offerMessage} onChange={event => setOfferMessage(event.target.value)} className="mt-3 min-h-20 w-full rounded-xl border bg-white p-3" placeholder="Optional note to the seller" /><Button type="submit" className="mt-3 bg-[#00843d]" disabled={offer.isPending}>Send offer</Button></form>}
        <div className="mt-6 rounded-2xl border border-slate-200 bg-white p-5"><div className="flex gap-4"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-[#00843d] text-white"><Store size={19} /></span><div className="min-w-0 flex-1"><p className="font-bold">{store.name} {store.isVerified && <ShieldCheck className="ml-1 inline text-[#00843d]" size={16} />}</p><p className="mt-1 text-sm text-slate-600">{store.isVerified ? "Verified seller" : "Seller"} · {store.location}</p><div className="mt-3 flex flex-wrap gap-3"><Link href={`/store/${store.slug}`} className="text-sm font-bold text-[#00843d]">Visit store</Link><button type="button" className="inline-flex items-center gap-1 text-sm font-bold text-[#00843d]" onClick={requestMessage}><MessageCircle size={15} /> Message seller</button></div>{messageOpen && <form onSubmit={event => { event.preventDefault(); if (!messageBody.trim()) { toast.error("Write a message for the seller."); return; } startMessage.mutate({ listingId: listing.id, body: messageBody }); }} className="mt-4"><textarea aria-label="Message seller" value={messageBody} onChange={event => setMessageBody(event.target.value)} className="min-h-20 w-full rounded-xl border bg-white p-3" placeholder="Ask the seller a product question" /><Button type="submit" size="sm" className="mt-2 bg-[#00843d]" disabled={startMessage.isPending}>Start conversation</Button></form>}</div></div><div className="mt-4 border-t border-slate-100 pt-4"><button type="button" className="inline-flex items-center gap-1 text-sm font-bold text-slate-600 hover:text-[#e31b23]" onClick={() => isAuthenticated ? setReportOpen(value => !value) : toast.error("Sign in to report a listing")}><Flag size={15} /> Report this listing</button>{reportOpen && <form onSubmit={event => { event.preventDefault(); report.mutate({ targetType: "LISTING", targetId: listing.id, reason: reportReason, details: reportDetails }); }} className="mt-3 rounded-xl bg-slate-50 p-4"><input required minLength={3} aria-label="Report reason" value={reportReason} onChange={event => setReportReason(event.target.value)} className="w-full rounded-lg border p-2.5" placeholder="Why are you reporting this listing?" /><textarea required minLength={10} aria-label="Report details" value={reportDetails} onChange={event => setReportDetails(event.target.value)} className="mt-3 min-h-20 w-full rounded-lg border p-2.5" placeholder="Describe the concern for the safety team." /><Button type="submit" size="sm" className="mt-3 bg-[#e31b23]" disabled={report.isPending}>Submit report</Button></form>}</div></div>
      </section>
    </div>
    <section className="mt-10 grid gap-8 lg:grid-cols-[1fr_360px]">
      <div id="reviews"><p className="eyebrow text-[#e31b23]">VERIFIED PURCHASES</p><h2 className="mt-2 text-2xl font-extrabold">Reviews from real buyers</h2>{productReviews.length ? <div className="mt-5 grid gap-4 md:grid-cols-2">{productReviews.map(({ review, buyer }) => <article key={review.id} className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-extrabold text-[#8a6500]">{"★".repeat(review.rating)}</p><p className="text-sm text-slate-500">Verified buyer: {buyer.name ?? "Marketplace member"}</p></div><p className="mt-3 text-sm leading-6 text-slate-700">{review.comment ?? "No written comment."}</p>{review.sellerResponse && <p className="mt-3 rounded-xl bg-[#eaf7ef] p-3 text-sm"><b>Seller response:</b> {review.sellerResponse}</p>}</article>)}</div> : <div className="mt-5 rounded-2xl border border-dashed border-slate-300 bg-white p-8 text-center"><p className="font-bold text-slate-700">No verified purchase reviews yet.</p><p className="mt-2 text-sm text-slate-500">Reviews appear after an eligible buyer completes a purchase.</p></div>}</div>
      <div><p className="eyebrow text-[#00843d]">BUYER GUIDANCE</p><h2 className="mt-2 text-2xl font-extrabold">Before you buy</h2><div className="mt-5 divide-y rounded-2xl bg-white ring-1 ring-slate-200">{faqItems.map(([question, answer]) => <div key={question}><button type="button" className="flex w-full items-center justify-between gap-4 p-4 text-left font-bold" aria-expanded={openFaq === question} onClick={() => setOpenFaq(openFaq === question ? null : question)}><span>{question}</span><ChevronDown className={`transition ${openFaq === question ? "rotate-180" : ""}`} size={18} /></button>{openFaq === question && <p className="px-4 pb-4 text-sm leading-6 text-slate-600">{answer}</p>}</div>)}</div></div>
    </section>
    {product.data.related.length > 0 ? <section className="mt-12"><div className="flex items-end justify-between"><div><p className="eyebrow text-[#00843d]">KEEP EXPLORING</p><h2 className="mt-2 text-2xl font-extrabold">More in {category.name}</h2></div><Link href={`/category/${category.slug}`} className="text-sm font-bold text-[#00843d]">View category</Link></div><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{product.data.related.map(({ listing: related, store: relatedStore, image: relatedImage }) => <Link href={`/product/${related.slug}`} key={related.id} className="overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-slate-200 transition hover:-translate-y-1"><div className="product-visual aspect-[1/.72]">{relatedImage?.url ? <img src={relatedImage.url} alt={related.title} className="h-full w-full object-cover" /> : <Package className="m-auto text-slate-300" size={36} />}</div><div className="p-4"><h3 className="line-clamp-2 font-extrabold text-[#111827]">{related.title}</h3><p className="mt-1 text-xs text-slate-500">{relatedStore.name}</p><p className="mt-3 text-lg font-extrabold text-[#e31b23]">{naira(related.priceKobo)}</p></div></Link>)}</div></section> : <section className="mt-12 rounded-2xl border border-dashed border-slate-300 bg-white p-6"><p className="font-extrabold">Explore more campus listings</p><p className="mt-1 text-sm text-slate-500">There are no related listings to show yet.</p><Link href="/explore" className="mt-4 inline-flex text-sm font-bold text-[#00843d]">Browse the catalogue</Link></section>}
  </main><div className="fixed inset-x-0 bottom-0 z-20 border-t border-slate-200 bg-white/95 p-3 shadow-[0_-8px_24px_rgba(15,23,42,.08)] backdrop-blur lg:hidden"><div className="mx-auto flex max-w-2xl items-center gap-3"><div className="min-w-0"><p className="truncate text-xs text-slate-500">{listing.title}</p><p className="font-black text-[#e31b23]">{naira(listing.priceKobo)}</p></div><Button className="ml-auto bg-[#e31b23] disabled:bg-slate-300" disabled={mutationPending || awaitingStock} onClick={addToCart}><ShoppingCart size={16} /> {awaitingStock ? "Awaiting" : "Add"}</Button><Button variant="outline" className="border-[#00843d] text-[#006b32]" disabled={mutationPending || awaitingStock} onClick={buy}>Buy</Button></div></div></div>;
}
