import { ArrowLeft, ExternalLink, FileText, Headphones, Mail, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import { Button } from "@/components/ui/button";

const LAST_UPDATED = "26 August 2026";

function UtilityShell({ eyebrow, title, description, children }: { eyebrow: string; title: string; description: string; children: React.ReactNode }) {
  return <main className="min-h-screen bg-[#f7f9fc] py-8 sm:py-12"><div className="page-shell"><Link href="/" className="inline-flex items-center gap-2 text-sm font-bold text-[#006b32] hover:underline"><ArrowLeft size={16} /> Back to marketplace</Link><article className="mt-6 overflow-hidden rounded-[2rem] bg-white shadow-sm ring-1 ring-slate-200"><header className="border-b border-slate-100 bg-[#eaf7ef] px-6 py-8 sm:px-10 sm:py-10"><p className="text-xs font-black uppercase tracking-[.16em] text-[#006b32]">{eyebrow}</p><h1 className="mt-3 max-w-3xl text-3xl font-black tracking-tight text-[#111827] sm:text-5xl">{title}</h1><p className="mt-4 max-w-2xl text-base leading-7 text-slate-700">{description}</p><p className="mt-5 text-xs font-bold uppercase tracking-[.12em] text-slate-500">Last updated: {LAST_UPDATED}</p></header><div className="px-6 py-8 sm:px-10 sm:py-10">{children}</div></article></div></main>;
}

function ReviewNotice() {
  return <aside className="rounded-2xl border border-[#f5b700]/40 bg-[#fff8e7] p-4 text-sm leading-6 text-[#694d00]"><p className="font-extrabold">Owner review required</p><p className="mt-1">This page is a truthful product-policy outline for ESUT Marketplace. The marketplace owner should review and approve the final legal wording before relying on it as formal legal advice or a complete contract.</p></aside>;
}

export function TermsPage() {
  return <UtilityShell eyebrow="MARKETPLACE TERMS" title="Terms of using ESUT Marketplace" description="A plain-language outline of the rules that currently shape buying, selling, campus pickup, and account use on ESUT Marketplace."><div className="max-w-3xl space-y-8 text-sm leading-7 text-slate-700"><ReviewNotice/><section><h2 className="text-xl font-extrabold text-slate-900">Marketplace role</h2><p className="mt-2">ESUT Marketplace provides a community marketplace for discovering listings and connecting buyers with sellers. A listing, seller profile, or store may be subject to review and may be unavailable when it does not meet marketplace requirements.</p></section><section><h2 className="text-xl font-extrabold text-slate-900">Buyer and seller responsibilities</h2><p className="mt-2">Buyers should review listing details, availability, seller information, pickup arrangements, and the final server-confirmed order before collecting an item. Sellers are responsible for truthful listing information, safe handover arrangements, accurate stock, and complying with applicable marketplace rules.</p></section><section><h2 className="text-xl font-extrabold text-slate-900">Campus pickup and payment</h2><p className="mt-2">The current checkout flow supports ESUT campus pickup and cash on pickup. The server rechecks price and stock before creating an order. Buyers should use a sensible public pickup point and should not send cash before collecting the item.</p></section><section><h2 className="text-xl font-extrabold text-slate-900">Safety and reports</h2><p className="mt-2">Users can report listings, stores, reviews, messages, or order-related issues through the available support and reporting flows. Reports are reviewed through the marketplace’s protected operational workflows; submitting a report does not guarantee a particular outcome.</p></section><section><h2 className="text-xl font-extrabold text-slate-900">Account and content</h2><p className="mt-2">Users must keep account credentials private and provide information that is accurate for the marketplace purpose. Do not upload unlawful, harmful, deceptive, or unauthorised content. The marketplace may restrict or review content and accounts under its approved policies.</p></section><div className="flex flex-wrap gap-3"><Link href="/privacy"><Button variant="outline"><ShieldCheck size={16}/> Read privacy outline</Button></Link><Link href="/support"><Button className="bg-[#e31b23] hover:bg-[#c9161d]"><Headphones size={16}/> Get support</Button></Link></div></div></UtilityShell>;
}

export function PrivacyPage() {
  return <UtilityShell eyebrow="PRIVACY OUTLINE" title="How ESUT Marketplace handles information" description="A clear product-level overview of account, marketplace, order, security, and media information. Final legal and regulatory wording remains subject to owner review."><div className="max-w-3xl space-y-8 text-sm leading-7 text-slate-700"><ReviewNotice/><section><h2 className="text-xl font-extrabold text-slate-900">Information used for the marketplace</h2><p className="mt-2">The application uses account information, listing and store details, cart and order records, messages, reports, reviews, security events, and notification preferences to operate the marketplace and protect users. The exact fields shown to other users depend on the public or protected context.</p></section><section><h2 className="text-xl font-extrabold text-slate-900">Public and private boundaries</h2><p className="mt-2">Public marketplace pages may show approved listing images, store information, product details, eligible public avatars, and published verified-purchase reviews. Account, order, security, evidence, and administrator information is intended to remain protected by authentication, ownership, and role checks.</p></section><section><h2 className="text-xl font-extrabold text-slate-900">Security and retention</h2><p className="mt-2">The service records security-relevant events and audit information needed to protect accounts and administer the marketplace. Passwords and reset tokens are not displayed as readable account content. Retention periods and any formal data-subject rights should be confirmed by the marketplace owner in the approved policy.</p></section><section><h2 className="text-xl font-extrabold text-slate-900">Media</h2><p className="mt-2">Approved public product media and eligible public avatars use the public media delivery layer. Verification evidence and other private case material remain in protected storage and should only be accessible to authorised workflows.</p></section><section><h2 className="text-xl font-extrabold text-slate-900">Questions or requests</h2><p className="mt-2">Use the protected support flow for account, order, privacy, or safety questions. Do not include passwords, reset tokens, or sensitive evidence in an ordinary message.</p></section><div className="flex flex-wrap gap-3"><Link href="/terms"><Button variant="outline"><FileText size={16}/> Read marketplace terms</Button></Link><Link href="/support"><Button className="bg-[#e31b23] hover:bg-[#c9161d]"><Headphones size={16}/> Open support</Button></Link></div></div></UtilityShell>;
}

export function SupportPage() {
  return <UtilityShell eyebrow="TRUST & SAFETY" title="ESUT Marketplace support" description="Choose the safest support path for account, order, listing, seller, or safety questions. No password or reset token is required to view this page."><div className="grid max-w-4xl gap-4 md:grid-cols-3"><section className="rounded-2xl bg-[#f7f9fc] p-5 ring-1 ring-slate-200"><Headphones className="text-[#00843d]" size={24}/><h2 className="mt-4 font-extrabold text-slate-900">Account support</h2><p className="mt-2 text-sm leading-6 text-slate-600">Use the protected account support workspace for account, order, saved-search, notification, and security questions.</p><Link href="/account/support" className="mt-4 inline-flex text-sm font-extrabold text-[#006b32] hover:underline">Open account support</Link></section><section className="rounded-2xl bg-[#f7f9fc] p-5 ring-1 ring-slate-200"><ShieldCheck className="text-[#00843d]" size={24}/><h2 className="mt-4 font-extrabold text-slate-900">Safety report</h2><p className="mt-2 text-sm leading-6 text-slate-600">Open a report from the relevant listing, store, review, message, or order context so ownership and evidence stay attached to the correct case.</p><Link href="/explore" className="mt-4 inline-flex text-sm font-extrabold text-[#006b32] hover:underline">Browse marketplace</Link></section><section className="rounded-2xl bg-[#f7f9fc] p-5 ring-1 ring-slate-200"><Mail className="text-[#00843d]" size={24}/><h2 className="mt-4 font-extrabold text-slate-900">General contact</h2><p className="mt-2 text-sm leading-6 text-slate-600">For a general question, use the contact page and choose the protected route that matches your situation. The service does not publish an unverified support email here.</p><Link href="/contact" className="mt-4 inline-flex text-sm font-extrabold text-[#006b32] hover:underline">Contact options</Link></section></div><div className="mt-8 rounded-2xl border border-slate-200 bg-white p-5 text-sm leading-6 text-slate-600"><p className="font-extrabold text-slate-900">Please do not send secrets</p><p className="mt-1">Never send your password, reset token, session cookie, or private seller-verification evidence through an unprotected channel.</p></div></UtilityShell>;
}

export function ContactPage() {
  return <UtilityShell eyebrow="CONTACT OPTIONS" title="Contact ESUT Marketplace" description="Use the route that keeps your question connected to the right marketplace context and protects private information."><div className="max-w-3xl space-y-5"><div className="rounded-2xl border border-[#00843d]/20 bg-[#eaf7ef] p-5 text-sm leading-6 text-[#164b2e]"><p className="font-extrabold">The safest contact route is contextual</p><p className="mt-1">Account, order, dispute, report, and security questions should be submitted from the authenticated workspace or the relevant marketplace page. This keeps ownership checks and private evidence boundaries in place.</p></div><div className="flex flex-wrap gap-3"><Link href="/support"><Button className="bg-[#e31b23] hover:bg-[#c9161d]"><Headphones size={16}/> View support routes</Button></Link><Link href="/account/support"><Button variant="outline"><ShieldCheck size={16}/> Account support</Button></Link><Link href="/explore"><Button variant="outline"><ExternalLink size={16}/> Browse marketplace</Button></Link></div><p className="text-sm leading-6 text-slate-600">For your protection, no email address, phone number, or legal contact identity is invented on this page. The marketplace owner can add an approved contact channel when one is available.</p></div></UtilityShell>;
}
