import { useAuth } from "@/_core/hooks/useAuth";
import { MarketplaceWorkspaceShell, type WorkspaceNavItem } from "@/components/MarketplaceWorkspaceShell";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { naira } from "@/lib/marketplace";
import { BarChart3, Boxes, ClipboardCheck, Heart, LayoutDashboard, MessageCircle, PackagePlus, Settings, ShoppingBag, Store, Tag, Truck } from "lucide-react";
import { Link, useLocation } from "wouter";
import { toast } from "sonner";

const sellerNavigation: WorkspaceNavItem[] = [
  { label: "Overview", href: "/seller", icon: LayoutDashboard },
  { label: "Products", href: "/seller/products", icon: ShoppingBag },
  { label: "Orders", href: "/seller/orders", icon: Truck },
  { label: "Inventory", href: "/seller/inventory", icon: Boxes },
  { label: "Offers", href: "/seller/offers", icon: Tag },
  { label: "Messages", href: "/seller/messages", icon: MessageCircle },
  { label: "Reviews", href: "/seller/reviews", icon: Heart },
  { label: "Analytics", href: "/seller/analytics", icon: BarChart3 },
  { label: "Store settings", href: "/seller/settings", icon: Settings },
];

export default function SellerDashboardPage() {
  const { user, loading, logout } = useAuth();
  const [, navigate] = useLocation();
  const isSeller = ["SELLER", "ADMIN", "SUPER_ADMIN"].includes(user?.role ?? "");
  const orders = trpc.seller.orders.useQuery({ page: 1, limit: 8 }, { enabled: isSeller });
  const analytics = trpc.seller.analytics.useQuery(undefined, { enabled: isSeller });
  const signOut = async () => { try { await logout(); toast.success("You have been signed out."); navigate("/"); } catch { toast.error("Unable to sign out. Please try again."); } };

  if (loading) return <main className="page-shell py-16">Loading seller workspace…</main>;
  if (!user) return <main className="page-shell py-20 text-center"><h1 className="text-3xl font-extrabold">Sign in to access seller tools</h1><Link href="/sell" className="mt-4 inline-block font-bold text-[#00843d]">Apply to sell</Link></main>;
  if (!isSeller) return <main className="page-shell py-20 text-center"><Store className="mx-auto text-[#00843d]" size={42} /><h1 className="mt-4 text-3xl font-extrabold">Seller approval required</h1><p className="mt-2 text-slate-600">Your store becomes available after an administrator approves your application.</p><Link href="/sell" className="mt-5 inline-block font-bold text-[#e31b23]">Check seller application</Link></main>;

  const summary = analytics.data;
  const recentOrders = orders.data ?? [];
  const peak = Math.max(...(summary?.last7Days.map(day => day.orderCount) ?? [0]), 1);
  const navigation = sellerNavigation.map(item => item.href === "/seller/orders" && summary?.activeOrders ? { ...item, badge: summary.activeOrders } : item.href === "/seller/inventory" && summary?.lowStockListings ? { ...item, badge: summary.lowStockListings } : item);

  return <MarketplaceWorkspaceShell kind="seller" eyebrow="SELLER OPERATIONS" title={`Good day, ${user.name ?? "seller"}`} subtitle="Run your verified ESUT store from one focused workspace. Every order, stock level, and performance signal below belongs only to your store." navItems={navigation} userName={user.name} onLogout={signOut} utility={<Link href="/seller/messages" className="rounded-xl border border-slate-200 px-3 py-2 text-sm font-bold text-slate-700 hover:border-[#00843d] hover:text-[#006b32]">Messages</Link>}>
    {(analytics.isError || orders.isError) && <div role="alert" className="mb-5 rounded-2xl bg-[#fff3f3] p-5 text-sm text-[#b91c1c] ring-1 ring-[#fecaca]"><p className="font-extrabold">Some store data could not be loaded.</p><div className="mt-3 flex flex-wrap gap-2">{analytics.isError && <Button size="sm" variant="outline" onClick={() => analytics.refetch()}>Retry performance data</Button>}{orders.isError && <Button size="sm" variant="outline" onClick={() => orders.refetch()}>Retry recent orders</Button>}</div></div>}
    <section aria-label="Store health summary" className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<BarChart3 />} tone="green" label="Completed sales" value={summary ? naira(summary.completedSalesKobo) : "—"} hint="Completed campus pickups" /><Metric icon={<ClipboardCheck />} tone="blue" label="Orders to action" value={summary?.activeOrders ?? "—"} hint={summary?.readyForPickupOrders ? `${summary.readyForPickupOrders} ready for pickup` : "Pending, confirmed, or processing"} /><Metric icon={<ShoppingBag />} tone="gold" label="Active listings" value={summary?.activeListings ?? "—"} hint={summary?.draftListings ? `${summary.draftListings} draft or pending` : "Published for buyers"} /><Metric icon={<Boxes />} tone="red" label="Stock attention" value={summary?.lowStockListings ?? "—"} hint={summary?.lowStockListings ? "Low or unavailable stock" : "No low-stock listings"} /></section>
    <section className="mt-6 grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><article className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-6"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.14em] text-[#00843d]">LAST 7 DAYS</p><h2 className="mt-1 text-xl font-black">Store activity</h2><p className="mt-1 text-sm text-slate-500">Real orders created for your store.</p></div><Link href="/seller/analytics" className="text-sm font-bold text-[#00843d]">Open analytics</Link></div>{analytics.isLoading ? <div className="mt-8 h-48 animate-pulse rounded-2xl bg-slate-100" /> : summary ? <><div className="mt-6 grid grid-cols-3 gap-3 rounded-2xl bg-[#f4f8f5] p-4"><MiniMetric label="Orders" value={summary.totalOrders} /><MiniMetric label="Completion" value={`${summary.completionRatePercent}%`} /><MiniMetric label="Buyer interest" value={summary.favoriteCount + summary.viewCount} /></div><div className="mt-7 flex h-40 items-end gap-2" aria-label="Seven-day order activity chart">{summary.last7Days.map(day => <div key={day.key} className="flex min-w-0 flex-1 flex-col items-center gap-2"><span className="text-xs font-bold text-slate-500">{day.orderCount || ""}</span><div className="w-full rounded-t-xl bg-[#00843d]" style={{ height: `${Math.max(8, Math.round((day.orderCount / peak) * 100))}%` }} title={`${day.label}: ${day.orderCount} order${day.orderCount === 1 ? "" : "s"}`} /><span className="text-xs font-semibold text-slate-500">{day.label}</span></div>)}</div><p className="sr-only">In the last seven days, your store recorded {summary.last7Days.reduce((total, day) => total + day.orderCount, 0)} orders.</p></> : <p className="mt-6 text-sm text-slate-500">Performance data is not available yet.</p>}</article>
      <article className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-6"><p className="text-xs font-black uppercase tracking-[.14em] text-[#e31b23]">PRIORITY TASKS</p><h2 className="mt-1 text-xl font-black">Quick actions</h2><div className="mt-5 grid gap-3"><QuickAction href="/seller/products/new" icon={<PackagePlus size={18} />} title="Add a product" detail="Create a new listing" /><QuickAction href="/seller/orders" icon={<Truck size={18} />} title="Process orders" detail={summary?.activeOrders ? `${summary.activeOrders} order${summary.activeOrders === 1 ? "" : "s"} need attention` : "Review store fulfilment"} /><QuickAction href="/seller/inventory" icon={<Boxes size={18} />} title="Update stock" detail={summary?.lowStockListings ? `${summary.lowStockListings} listing${summary.lowStockListings === 1 ? "" : "s"} need stock attention` : "Review available units"} /><QuickAction href="/seller/offers" icon={<Tag size={18} />} title="Manage offers" detail={summary?.receivedOfferCount ? `${summary.receivedOfferCount} received offer${summary.receivedOfferCount === 1 ? "" : "s"}` : "Review buyer offers"} /></div></article></section>
    <section className="mt-6 grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><article className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[.14em] text-[#00843d]">ORDER FLOW</p><h2 className="mt-1 text-xl font-black">Recent orders</h2></div><Link href="/seller/orders" className="text-sm font-bold text-[#00843d]">View all</Link></div>{orders.isLoading ? <div className="mt-5 space-y-3"><div className="h-14 animate-pulse rounded-xl bg-slate-100" /><div className="h-14 animate-pulse rounded-xl bg-slate-100" /></div> : orders.isError ? <p className="mt-5 text-sm text-slate-500">Recent orders are temporarily unavailable. Use the retry control above.</p> : recentOrders.length ? <div className="mt-5 divide-y divide-slate-100">{recentOrders.map(({ order }) => <Link href={`/seller/orders/${order.publicId}`} className="flex items-center justify-between gap-4 py-4 transition hover:bg-slate-50" key={order.id}><div><p className="font-extrabold">{order.publicId}</p><p className="mt-1 text-sm text-slate-500">{new Date(order.createdAt).toLocaleDateString("en-NG", { day: "numeric", month: "short" })}</p></div><div className="text-right"><p className="font-extrabold">{naira(order.totalKobo)}</p><span className="mt-1 inline-flex rounded-full bg-[#eaf7ef] px-2 py-0.5 text-xs font-black text-[#006b32]">{order.status.replaceAll("_", " ")}</span></div></Link>)}</div> : <Empty icon={<Truck size={26} />} title="No orders received yet" copy="When a buyer places a campus-pickup order for your listings, it will appear here." href="/seller/products/new" label="Add a product" />}</article><article className="rounded-3xl bg-[#08243b] p-5 text-white shadow-sm sm:p-6"><p className="text-xs font-black uppercase tracking-[.14em] text-[#f5b700]">STORE HEALTH</p><h2 className="mt-1 text-xl font-black">Inventory and buyer interest</h2><div className="mt-6 grid gap-4 sm:grid-cols-3 xl:grid-cols-1"><DarkMetric label="Available units" value={summary?.availableUnits ?? "—"} /><DarkMetric label="Listing views" value={summary?.viewCount ?? "—"} /><DarkMetric label="Saved by buyers" value={summary?.favoriteCount ?? "—"} /></div><Link href="/seller/store" className="mt-6 inline-flex text-sm font-bold text-[#f5b700]">Review your store profile →</Link></article></section>
  </MarketplaceWorkspaceShell>;
}

function Metric({ icon, tone, label, value, hint }: { icon: React.ReactNode; tone: "green" | "blue" | "gold" | "red"; label: string; value: string | number; hint: string }) { const palette = { green: "bg-[#eaf7ef] text-[#006b32]", blue: "bg-[#edf6ff] text-[#0570c0]", gold: "bg-[#fff7e6] text-[#8a6500]", red: "bg-[#fff3f3] text-[#b91c1c]" }[tone]; return <article className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><span className={`flex h-10 w-10 items-center justify-center rounded-xl ${palette}`}>{icon}</span><p className="mt-5 text-2xl font-black">{value}</p><p className="mt-1 font-bold">{label}</p><p className="mt-1 text-xs leading-5 text-slate-500">{hint}</p></article>; }
function MiniMetric({ label, value }: { label: string; value: string | number }) { return <div><p className="text-xs font-bold text-slate-500">{label}</p><p className="mt-1 text-lg font-black text-[#10263c]">{value}</p></div>; }
function QuickAction({ href, icon, title, detail }: { href: string; icon: React.ReactNode; title: string; detail: string }) { return <Link href={href} className="flex items-center gap-3 rounded-2xl border border-slate-200 p-4 transition hover:border-[#00843d] hover:bg-[#f4f8f5]"><span className="text-[#00843d]">{icon}</span><span className="min-w-0 flex-1"><span className="block font-extrabold">{title}</span><span className="mt-0.5 block text-xs text-slate-500">{detail}</span></span><span aria-hidden className="text-lg font-black text-[#00843d]">→</span></Link>; }
function Empty({ icon, title, copy, href, label }: { icon: React.ReactNode; title: string; copy: string; href: string; label: string }) { return <div className="mt-5 rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-7 text-center"><span className="mx-auto flex h-11 w-11 items-center justify-center rounded-full bg-white text-[#00843d] shadow-sm">{icon}</span><p className="mt-3 font-extrabold">{title}</p><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-500">{copy}</p><Link href={href} className="mt-4 inline-flex text-sm font-bold text-[#00843d]">{label}</Link></div>; }
function DarkMetric({ label, value }: { label: string; value: string | number }) { return <div className="rounded-2xl bg-white/10 p-4 ring-1 ring-white/10"><p className="text-xs font-bold text-slate-300">{label}</p><p className="mt-1 text-2xl font-black text-white">{value}</p></div>; }
