-- Approved ESUT Marketplace final category hierarchy.
-- This migration preserves all existing top-level category rows and listing assignments.
-- It only inserts or updates the specified child records by their unique slugs.

INSERT INTO categories (parentId, name, slug, description, icon, imageUrl, isFeatured, isActive, sortOrder) VALUES
  (1, 'TVs & Home Entertainment', 'tvs-home-entertainment', NULL, NULL, NULL, 0, 1, 0),
  (1, 'Audio & Speakers', 'audio-speakers', NULL, NULL, NULL, 0, 1, 1),
  (1, 'Cameras & Photography', 'cameras-photography', NULL, NULL, NULL, 0, 1, 2),
  (1, 'Smart Home Devices', 'smart-home-devices', NULL, NULL, NULL, 0, 1, 3),
  (1, 'Power & Electrical', 'power-electrical', NULL, NULL, NULL, 0, 1, 4),
  (1, 'Lighting', 'lighting', NULL, NULL, NULL, 0, 1, 5),
  (1, 'Home Appliances', 'home-appliances', NULL, NULL, NULL, 0, 1, 6),
  (1, 'Gaming & Consoles', 'gaming-consoles', NULL, NULL, NULL, 0, 1, 7),
  (1, 'Electronic Accessories', 'electronic-accessories', NULL, NULL, NULL, 0, 1, 8),
  (1, 'Other Electronics', 'other-electronics', NULL, NULL, NULL, 0, 1, 9),
  (3, 'Smartphones', 'smartphones', NULL, NULL, NULL, 0, 1, 0),
  (3, 'Feature Phones', 'feature-phones', NULL, NULL, NULL, 0, 1, 1),
  (3, 'Phone Cases & Covers', 'phone-cases-covers', NULL, NULL, NULL, 0, 1, 2),
  (3, 'Screen Protectors', 'screen-protectors', NULL, NULL, NULL, 0, 1, 3),
  (3, 'Chargers & Cables', 'chargers-cables', NULL, NULL, NULL, 0, 1, 4),
  (3, 'Power Banks', 'power-banks', NULL, NULL, NULL, 0, 1, 5),
  (3, 'Earphones & Headsets', 'earphones-headsets', NULL, NULL, NULL, 0, 1, 6),
  (3, 'Smartwatches & Wearables', 'smartwatches-wearables', NULL, NULL, NULL, 0, 1, 7),
  (3, 'Phone Holders & Stands', 'phone-holders-stands', NULL, NULL, NULL, 0, 1, 8),
  (3, 'Other Phone Products', 'other-phone-products', NULL, NULL, NULL, 0, 1, 9),
  (8, 'Laptops', 'laptops', NULL, NULL, NULL, 0, 1, 0),
  (8, 'Desktop Computers', 'desktop-computers', NULL, NULL, NULL, 0, 1, 1),
  (8, 'Monitors', 'monitors', NULL, NULL, NULL, 0, 1, 2),
  (8, 'Tablets', 'tablets', NULL, NULL, NULL, 0, 1, 3),
  (8, 'Computer Accessories', 'computer-accessories', NULL, NULL, NULL, 0, 1, 4),
  (8, 'Keyboards & Mice', 'keyboards-mice', NULL, NULL, NULL, 0, 1, 5),
  (8, 'Storage Devices', 'storage-devices', NULL, NULL, NULL, 0, 1, 6),
  (8, 'RAM & Memory', 'ram-memory', NULL, NULL, NULL, 0, 1, 7),
  (8, 'PC Components', 'pc-components', NULL, NULL, NULL, 0, 1, 8),
  (8, 'Printers & Scanners', 'printers-scanners', NULL, NULL, NULL, 0, 1, 9),
  (8, 'Networking', 'networking', NULL, NULL, NULL, 0, 1, 10),
  (8, 'Laptop Chargers & Adapters', 'laptop-chargers-adapters', NULL, NULL, NULL, 0, 1, 11),
  (8, 'Computer Bags & Cases', 'computer-bags-cases', NULL, NULL, NULL, 0, 1, 12),
  (8, 'Other Computing', 'other-computing', NULL, NULL, NULL, 0, 1, 13),
  (2, 'Men''s Clothing', 'mens-clothing', NULL, NULL, NULL, 0, 1, 0),
  (2, 'Women''s Clothing', 'womens-clothing', NULL, NULL, NULL, 0, 1, 1),
  (2, 'Shoes & Footwear', 'shoes-footwear', NULL, NULL, NULL, 0, 1, 2),
  (2, 'Bags', 'bags', NULL, NULL, NULL, 0, 1, 3),
  (2, 'Watches', 'watches', NULL, NULL, NULL, 0, 1, 4),
  (2, 'Jewelry', 'jewelry', NULL, NULL, NULL, 0, 1, 5),
  (2, 'Fashion Accessories', 'fashion-accessories', NULL, NULL, NULL, 0, 1, 6),
  (2, 'Traditional & Cultural Wear', 'traditional-cultural-wear', NULL, NULL, NULL, 0, 1, 7),
  (2, 'Underwear & Loungewear', 'underwear-loungewear', NULL, NULL, NULL, 0, 1, 8),
  (2, 'Sportswear', 'sportswear', NULL, NULL, NULL, 0, 1, 9),
  (2, 'Uniforms', 'uniforms', NULL, NULL, NULL, 0, 1, 10),
  (2, 'Other Fashion', 'other-fashion', NULL, NULL, NULL, 0, 1, 11),
  (4, 'Skincare', 'skincare', NULL, NULL, NULL, 0, 1, 0),
  (4, 'Haircare & Hair Products', 'haircare-hair-products', NULL, NULL, NULL, 0, 1, 1),
  (4, 'Makeup & Cosmetics', 'makeup-cosmetics', NULL, NULL, NULL, 0, 1, 2),
  (4, 'Bath & Body Care', 'bath-body-care', NULL, NULL, NULL, 0, 1, 3),
  (4, 'Personal Hygiene', 'personal-hygiene', NULL, NULL, NULL, 0, 1, 4),
  (4, 'Fragrances & Perfumes', 'fragrances-perfumes', NULL, NULL, NULL, 0, 1, 5),
  (4, 'Beauty Tools & Accessories', 'beauty-tools-accessories', NULL, NULL, NULL, 0, 1, 6),
  (7, 'Academic & Education', 'academic-education', NULL, NULL, NULL, 0, 1, 0),
  (7, 'Technology & Digital', 'technology-digital', NULL, NULL, NULL, 0, 1, 1),
  (7, 'Repairs & Maintenance', 'repairs-maintenance', NULL, NULL, NULL, 0, 1, 2),
  (7, 'Photography & Media', 'photography-media', NULL, NULL, NULL, 0, 1, 3),
  (7, 'Fashion & Beauty Services', 'fashion-beauty-services', NULL, NULL, NULL, 0, 1, 4),
  (7, 'Home & Personal Services', 'home-personal-services', NULL, NULL, NULL, 0, 1, 5),
  (7, 'Events & Entertainment', 'events-entertainment', NULL, NULL, NULL, 0, 1, 6),
  (7, 'Transport & Delivery', 'transport-delivery', NULL, NULL, NULL, 0, 1, 7),
  (6, 'ESUT Chop', 'esut-chop', NULL, NULL, NULL, 0, 1, 0),
  (30001, 'Digital Academic Resources', 'digital-academic-resources', NULL, NULL, NULL, 0, 1, 0),
  (5, 'ESUT Accommodation', 'esut-accommodation', NULL, NULL, NULL, 0, 1, 0)
ON DUPLICATE KEY UPDATE
  parentId = VALUES(parentId),
  name = VALUES(name),
  isActive = VALUES(isActive),
  sortOrder = VALUES(sortOrder);
