from pathlib import Path

path = Path("server/routers.ts")
text = path.read_text()

start = text.index("const notifySearchAlertsForListing")
end = text.index("\nconst affectedRows", start)
new_helper = '''const notifySearchAlertsForListing = async (tx: any, listingId: number) => { const row = (await tx.select({ listing: listings, store: stores, category: categories }).from(listings).innerJoin(stores, eq(listings.storeId, stores.id)).innerJoin(categories, eq(listings.categoryId, categories.id)).where(eq(listings.id, listingId)).limit(1))[0]; if (!row || row.listing.status !== "ACTIVE" || row.store.status !== "ACTIVE") return 0; const activeAlerts = await tx.select({ alert: searchAlerts, user: users }).from(searchAlerts).innerJoin(users, eq(searchAlerts.userId, users.id)).where(eq(searchAlerts.status, "ACTIVE")).limit(500); const haystack = `${row.listing.title} ${row.store.name} ${row.category.name} ${row.category.slug}`.toLocaleLowerCase(); const matches = activeAlerts.filter(({ alert }: { alert: typeof searchAlerts.$inferSelect }) => { const phraseMatches = haystack.includes(alert.query.toLocaleLowerCase()); const categoryMatches = !alert.categorySlug || alert.categorySlug === row.category.slug; const priceMatches = (alert.minKobo == null || row.listing.priceKobo >= alert.minKobo) && (alert.maxKobo == null || row.listing.priceKobo <= alert.maxKobo); const conditionMatches = !alert.condition || alert.condition === row.listing.condition; const verifiedMatches = !alert.verified || row.store.isVerified; return phraseMatches && categoryMatches && priceMatches && conditionMatches && verifiedMatches && alert.userId !== row.store.ownerUserId; }); if (!matches.length) return 0; const inAppMatches = matches.filter(({ alert }) => alert.notifyInApp); if (inAppMatches.length) await tx.insert(notifications).values(inAppMatches.map(({ alert }) => ({ userId: alert.userId, type: "SEARCH_ALERT_MATCH", title: "A listing matches your saved search", message: `“${row.listing.title}” is now available in the marketplace.`, targetRoute: `/product/${row.listing.slug}` }))); for (const { alert, user } of matches) { if (alert.notifyEmail && user.email) { const template = await renderManagedEmailTemplate("search_alert_match", { name: user.name ?? "there", listingTitle: row.listing.title, dashboardUrl: `/product/${row.listing.slug}` }); await sendTransactionalEmail({ to: user.email, subject: template.subject, text: template.body }, "searchAlerts"); } } await tx.update(searchAlerts).set({ lastNotifiedAt: new Date() }).where(inArray(searchAlerts.id, matches.map(({ alert }) => alert.id))); return matches.length; };'''
text = text[:start] + new_helper + text[end:]

start = text.index("  searchAlerts: router({")
end = text.index("\n  profile: router({", start)
new_router = '''  searchAlerts: router({
    listMine: protectedProcedure.query(async ({ ctx }) => (await ensureDb()).select().from(searchAlerts).where(eq(searchAlerts.userId, ctx.user.id)).orderBy(desc(searchAlerts.createdAt))),
    create: protectedProcedure.input(searchAlertInput).mutation(async ({ ctx, input }) => { const db = await ensureDb(); const existing = (await db.select().from(searchAlerts).where(and(eq(searchAlerts.userId, ctx.user.id), eq(searchAlerts.status, "ACTIVE"), eq(searchAlerts.query, input.query))).limit(20)).find(alert => alert.categorySlug === (input.categorySlug ?? null) && alert.minKobo === (input.minKobo ?? null) && alert.maxKobo === (input.maxKobo ?? null) && alert.condition === (input.condition ?? null) && alert.verified === input.verified); if (existing) return { id: existing.id, reactivated: false }; const created = await db.insert(searchAlerts).values({ userId: ctx.user.id, query: input.query, categorySlug: input.categorySlug ?? null, minKobo: input.minKobo ?? null, maxKobo: input.maxKobo ?? null, condition: input.condition ?? null, verified: input.verified, notifyInApp: input.notifyInApp, notifyEmail: input.notifyEmail }); const id = Number(created[0].insertId); await db.insert(auditLogs).values({ actorUserId: ctx.user.id, action: "SEARCH_ALERT_CREATED", targetType: "SEARCH_ALERT", targetId: String(id), metadata: { query: input.query, hasCategory: Boolean(input.categorySlug), hasPriceBounds: input.minKobo !== undefined || input.maxKobo !== undefined, verified: input.verified, notifyInApp: input.notifyInApp, notifyEmail: input.notifyEmail } }); return { id, reactivated: false }; }),
    update: protectedProcedure.input(z.object({ id: z.number().int().positive() }).merge(searchAlertInput)).mutation(async ({ ctx, input }) => { const db = await ensureDb(); const alert = (await db.select().from(searchAlerts).where(and(eq(searchAlerts.id, input.id), eq(searchAlerts.userId, ctx.user.id), eq(searchAlerts.status, "ACTIVE"))).limit(1))[0]; if (!alert) throw new TRPCError({ code: "NOT_FOUND", message: "Active search alert not found." }); const duplicate = (await db.select({ id: searchAlerts.id }).from(searchAlerts).where(and(eq(searchAlerts.userId, ctx.user.id), eq(searchAlerts.status, "ACTIVE"), eq(searchAlerts.query, input.query), ne(searchAlerts.id, input.id))).limit(20)).find(row => row.id !== input.id); if (duplicate) throw new TRPCError({ code: "CONFLICT", message: "An active saved search already uses these words." }); await db.update(searchAlerts).set({ query: input.query, categorySlug: input.categorySlug ?? null, minKobo: input.minKobo ?? null, maxKobo: input.maxKobo ?? null, condition: input.condition ?? null, verified: input.verified, notifyInApp: input.notifyInApp, notifyEmail: input.notifyEmail }).where(and(eq(searchAlerts.id, input.id), eq(searchAlerts.userId, ctx.user.id), eq(searchAlerts.status, "ACTIVE"))); await db.insert(auditLogs).values({ actorUserId: ctx.user.id, action: "SEARCH_ALERT_UPDATED", targetType: "SEARCH_ALERT", targetId: String(input.id), metadata: { hasCategory: Boolean(input.categorySlug), hasPriceBounds: input.minKobo !== undefined || input.maxKobo !== undefined, verified: input.verified, notifyInApp: input.notifyInApp, notifyEmail: input.notifyEmail } }); return { success: true }; }),
    cancel: protectedProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const db = await ensureDb(); const changed = await db.update(searchAlerts).set({ status: "CANCELLED" }).where(and(eq(searchAlerts.id, input.id), eq(searchAlerts.userId, ctx.user.id), eq(searchAlerts.status, "ACTIVE"))); if (!affectedRows(changed)) throw new TRPCError({ code: "NOT_FOUND", message: "Active search alert not found." }); await db.insert(auditLogs).values({ actorUserId: ctx.user.id, action: "SEARCH_ALERT_CANCELLED", targetType: "SEARCH_ALERT", targetId: String(input.id), metadata: { ownerAction: true } }); return { success: true }; }),
  }),'''
text = text[:start] + new_router + text[end:]
path.write_text(text)
print("updated saved-alert router blocks")
''
